<?php

namespace TolgaKaragol\Emoji;

/**
 * Class AllEmoji
 * @package TolgaKaragol\Emoji\AllEmoji
 *
 * @property string grinningFace 😀
 * @property string grinningFaceWithBigEyes 😃
 * @property string grinningFaceWithSmilingEyes 😄
 * @property string beamingFaceWithSmilingEyes 😁
 * @property string grinningSquintingFace 😆
 * @property string grinningFaceWithSweat 😅
 * @property string rollingOnTheFloorLaughing 🤣
 * @property string faceWithTearsOfJoy 😂
 * @property string slightlySmilingFace 🙂
 * @property string upsideDownFace 🙃
 * @property string winkingFace 😉
 * @property string smilingFaceWithSmilingEyes 😊
 * @property string smilingFaceWithHalo 😇
 * @property string smilingFaceWithHearts 🥰
 * @property string smilingFaceWithHeartEyes 😍
 * @property string starStruck 🤩
 * @property string faceBlowingAKiss 😘
 * @property string kissingFace 😗
 * @property string smilingFace ☺
 * @property string kissingFaceWithClosedEyes 😚
 * @property string kissingFaceWithSmilingEyes 😙
 * @property string faceSavoringFood 😋
 * @property string faceWithTongue 😛
 * @property string winkingFaceWithTongue 😜
 * @property string zanyFace 🤪
 * @property string squintingFaceWithTongue 😝
 * @property string moneyMouthFace 🤑
 * @property string huggingFace 🤗
 * @property string faceWithHandOverMouth 🤭
 * @property string shushingFace 🤫
 * @property string thinkingFace 🤔
 * @property string zipperMouthFace 🤐
 * @property string faceWithRaisedEyebrow 🤨
 * @property string neutralFace 😐
 * @property string expressionlessFace 😑
 * @property string faceWithoutMouth 😶
 * @property string smirkingFace 😏
 * @property string unamusedFace 😒
 * @property string faceWithRollingEyes 🙄
 * @property string grimacingFace 😬
 * @property string lyingFace 🤥
 * @property string relievedFace 😌
 * @property string pensiveFace 😔
 * @property string sleepyFace 😪
 * @property string droolingFace 🤤
 * @property string sleepingFace 😴
 * @property string faceWithMedicalMask 😷
 * @property string faceWithThermometer 🤒
 * @property string faceWithHeadBandage 🤕
 * @property string nauseatedFace 🤢
 * @property string faceVomiting 🤮
 * @property string sneezingFace 🤧
 * @property string hotFace 🥵
 * @property string coldFace 🥶
 * @property string woozyFace 🥴
 * @property string dizzyFace 😵
 * @property string explodingHead 🤯
 * @property string cowboyHatFace 🤠
 * @property string partyingFace 🥳
 * @property string smilingFaceWithSunglasses 😎
 * @property string nerdFace 🤓
 * @property string faceWithMonocle 🧐
 * @property string confusedFace 😕
 * @property string worriedFace 😟
 * @property string slightlyFrowningFace 🙁
 * @property string frowningFace ☹
 * @property string faceWithOpenMouth 😮
 * @property string hushedFace 😯
 * @property string astonishedFace 😲
 * @property string flushedFace 😳
 * @property string pleadingFace 🥺
 * @property string frowningFaceWithOpenMouth 😦
 * @property string anguishedFace 😧
 * @property string fearfulFace 😨
 * @property string anxiousFaceWithSweat 😰
 * @property string sadButRelievedFace 😥
 * @property string cryingFace 😢
 * @property string loudlyCryingFace 😭
 * @property string faceScreamingInFear 😱
 * @property string confoundedFace 😖
 * @property string perseveringFace 😣
 * @property string disappointedFace 😞
 * @property string downcastFaceWithSweat 😓
 * @property string wearyFace 😩
 * @property string tiredFace 😫
 * @property string yawningFace 🥱
 * @property string faceWithSteamFromNose 😤
 * @property string poutingFace 😡
 * @property string angryFace 😠
 * @property string faceWithSymbolsOnMouth 🤬
 * @property string smilingFaceWithHorns 😈
 * @property string angryFaceWithHorns 👿
 * @property string skull 💀
 * @property string skullAndCrossbones ☠
 * @property string pileOfPoo 💩
 * @property string clownFace 🤡
 * @property string ogre 👹
 * @property string goblin 👺
 * @property string ghost 👻
 * @property string alien 👽
 * @property string alienMonster 👾
 * @property string robot 🤖
 * @property string grinningCat 😺
 * @property string grinningCatWithSmilingEyes 😸
 * @property string catWithTearsOfJoy 😹
 * @property string smilingCatWithHeartEyes 😻
 * @property string catWithWrySmile 😼
 * @property string kissingCat 😽
 * @property string wearyCat 🙀
 * @property string cryingCat 😿
 * @property string poutingCat 😾
 * @property string seeNoEvilMonkey 🙈
 * @property string hearNoEvilMonkey 🙉
 * @property string speakNoEvilMonkey 🙊
 * @property string kissMark 💋
 * @property string loveLetter 💌
 * @property string heartWithArrow 💘
 * @property string heartWithRibbon 💝
 * @property string sparklingHeart 💖
 * @property string growingHeart 💗
 * @property string beatingHeart 💓
 * @property string revolvingHearts 💞
 * @property string twoHearts 💕
 * @property string heartDecoration 💟
 * @property string heartExclamation ❣
 * @property string brokenHeart 💔
 * @property string redHeart ❤
 * @property string orangeHeart 🧡
 * @property string yellowHeart 💛
 * @property string greenHeart 💚
 * @property string blueHeart 💙
 * @property string purpleHeart 💜
 * @property string brownHeart 🤎
 * @property string blackHeart 🖤
 * @property string whiteHeart 🤍
 * @property string hundredPoints 💯
 * @property string angerSymbol 💢
 * @property string collision 💥
 * @property string dizzy 💫
 * @property string sweatDroplets 💦
 * @property string dashingAway 💨
 * @property string hole 🕳
 * @property string bomb 💣
 * @property string speechBalloon 💬
 * @property string eyeInSpeechBubble &amp;#x1f441&amp;#xfe0f&amp;#x200d&amp;#x1f5e8️
 * @property string leftSpeechBubble 🗨
 * @property string rightAngerBubble 🗯
 * @property string thoughtBalloon 💭
 * @property string zzz 💤
 * @property string wavingHand 👋
 * @property string raisedBackOfHand 🤚
 * @property string handWithFingersSplayed 🖐
 * @property string raisedHand ✋
 * @property string vulcanSalute 🖖
 * @property string oKHand 👌
 * @property string pinchingHand 🤏
 * @property string victoryHand ✌
 * @property string crossedFingers 🤞
 * @property string loveYouGesture 🤟
 * @property string signOfTheHorns 🤘
 * @property string callMeHand 🤙
 * @property string backhandIndexPointingLeft 👈
 * @property string backhandIndexPointingRight 👉
 * @property string backhandIndexPointingUp 👆
 * @property string middleFinger 🖕
 * @property string backhandIndexPointingDown 👇
 * @property string indexPointingUp ☝
 * @property string thumbsUp 👍
 * @property string thumbsDown 👎
 * @property string raisedFist ✊
 * @property string oncomingFist 👊
 * @property string leftFacingFist 🤛
 * @property string rightFacingFist 🤜
 * @property string clappingHands 👏
 * @property string raisingHands 🙌
 * @property string openHands 👐
 * @property string palmsUpTogether 🤲
 * @property string handshake 🤝
 * @property string foldedHands 🙏
 * @property string writingHand ✍
 * @property string nailPolish 💅
 * @property string selfie 🤳
 * @property string flexedBiceps 💪
 * @property string mechanicalArm 🦾
 * @property string mechanicalLeg 🦿
 * @property string leg 🦵
 * @property string foot 🦶
 * @property string ear 👂
 * @property string earWithHearingAid 🦻
 * @property string nose 👃
 * @property string brain 🧠
 * @property string tooth 🦷
 * @property string bone 🦴
 * @property string eyes 👀
 * @property string eye 👁
 * @property string tongue 👅
 * @property string mouth 👄
 * @property string baby 👶
 * @property string child 🧒
 * @property string boy 👦
 * @property string girl 👧
 * @property string person 🧑
 * @property string personBlondHair 👱
 * @property string man 👨
 * @property string manBeard 🧔
 * @property string manRedHair &amp;#x1f468&amp;#x200d🦰
 * @property string manCurlyHair &amp;#x1f468&amp;#x200d🦱
 * @property string manWhiteHair &amp;#x1f468&amp;#x200d🦳
 * @property string manBald &amp;#x1f468&amp;#x200d🦲
 * @property string woman 👩
 * @property string womanRedHair &amp;#x1f469&amp;#x200d🦰
 * @property string personRedHair &amp;#x1f9d1&amp;#x200d🦰
 * @property string womanCurlyHair &amp;#x1f469&amp;#x200d🦱
 * @property string personCurlyHair &amp;#x1f9d1&amp;#x200d🦱
 * @property string womanWhiteHair &amp;#x1f469&amp;#x200d🦳
 * @property string personWhiteHair &amp;#x1f9d1&amp;#x200d🦳
 * @property string womanBald &amp;#x1f469&amp;#x200d🦲
 * @property string personBald &amp;#x1f9d1&amp;#x200d🦲
 * @property string womanBlondHair &amp;#x1f471&amp;#x200d&amp;#x2640️
 * @property string manBlondHair &amp;#x1f471&amp;#x200d&amp;#x2642️
 * @property string olderPerson 🧓
 * @property string oldMan 👴
 * @property string oldWoman 👵
 * @property string personFrowning 🙍
 * @property string manFrowning &amp;#x1f64d&amp;#x200d&amp;#x2642️
 * @property string womanFrowning &amp;#x1f64d&amp;#x200d&amp;#x2640️
 * @property string personPouting 🙎
 * @property string manPouting &amp;#x1f64e&amp;#x200d&amp;#x2642️
 * @property string womanPouting &amp;#x1f64e&amp;#x200d&amp;#x2640️
 * @property string personGesturingNO 🙅
 * @property string manGesturingNO &amp;#x1f645&amp;#x200d&amp;#x2642️
 * @property string womanGesturingNO &amp;#x1f645&amp;#x200d&amp;#x2640️
 * @property string personGesturingOK 🙆
 * @property string manGesturingOK &amp;#x1f646&amp;#x200d&amp;#x2642️
 * @property string womanGesturingOK &amp;#x1f646&amp;#x200d&amp;#x2640️
 * @property string personTippingHand 💁
 * @property string manTippingHand &amp;#x1f481&amp;#x200d&amp;#x2642️
 * @property string womanTippingHand &amp;#x1f481&amp;#x200d&amp;#x2640️
 * @property string personRaisingHand 🙋
 * @property string manRaisingHand &amp;#x1f64b&amp;#x200d&amp;#x2642️
 * @property string womanRaisingHand &amp;#x1f64b&amp;#x200d&amp;#x2640️
 * @property string deafPerson 🧏
 * @property string deafMan &amp;#x1f9cf&amp;#x200d&amp;#x2642️
 * @property string deafWoman &amp;#x1f9cf&amp;#x200d&amp;#x2640️
 * @property string personBowing 🙇
 * @property string manBowing &amp;#x1f647&amp;#x200d&amp;#x2642️
 * @property string womanBowing &amp;#x1f647&amp;#x200d&amp;#x2640️
 * @property string personFacepalming 🤦
 * @property string manFacepalming &amp;#x1f926&amp;#x200d&amp;#x2642️
 * @property string womanFacepalming &amp;#x1f926&amp;#x200d&amp;#x2640️
 * @property string personShrugging 🤷
 * @property string manShrugging &amp;#x1f937&amp;#x200d&amp;#x2642️
 * @property string womanShrugging &amp;#x1f937&amp;#x200d&amp;#x2640️
 * @property string healthWorker &amp;#x1f9d1&amp;#x200d&amp;#x2695️
 * @property string manHealthWorker &amp;#x1f468&amp;#x200d&amp;#x2695️
 * @property string womanHealthWorker &amp;#x1f469&amp;#x200d&amp;#x2695️
 * @property string student &amp;#x1f9d1&amp;#x200d🎓
 * @property string manStudent &amp;#x1f468&amp;#x200d🎓
 * @property string womanStudent &amp;#x1f469&amp;#x200d🎓
 * @property string teacher &amp;#x1f9d1&amp;#x200d🏫
 * @property string manTeacher &amp;#x1f468&amp;#x200d🏫
 * @property string womanTeacher &amp;#x1f469&amp;#x200d🏫
 * @property string judge &amp;#x1f9d1&amp;#x200d&amp;#x2696️
 * @property string manJudge &amp;#x1f468&amp;#x200d&amp;#x2696️
 * @property string womanJudge &amp;#x1f469&amp;#x200d&amp;#x2696️
 * @property string farmer &amp;#x1f9d1&amp;#x200d🌾
 * @property string manFarmer &amp;#x1f468&amp;#x200d🌾
 * @property string womanFarmer &amp;#x1f469&amp;#x200d🌾
 * @property string cook &amp;#x1f9d1&amp;#x200d🍳
 * @property string manCook &amp;#x1f468&amp;#x200d🍳
 * @property string womanCook &amp;#x1f469&amp;#x200d🍳
 * @property string mechanic &amp;#x1f9d1&amp;#x200d🔧
 * @property string manMechanic &amp;#x1f468&amp;#x200d🔧
 * @property string womanMechanic &amp;#x1f469&amp;#x200d🔧
 * @property string factoryWorker &amp;#x1f9d1&amp;#x200d🏭
 * @property string manFactoryWorker &amp;#x1f468&amp;#x200d🏭
 * @property string womanFactoryWorker &amp;#x1f469&amp;#x200d🏭
 * @property string officeWorker &amp;#x1f9d1&amp;#x200d💼
 * @property string manOfficeWorker &amp;#x1f468&amp;#x200d💼
 * @property string womanOfficeWorker &amp;#x1f469&amp;#x200d💼
 * @property string scientist &amp;#x1f9d1&amp;#x200d🔬
 * @property string manScientist &amp;#x1f468&amp;#x200d🔬
 * @property string womanScientist &amp;#x1f469&amp;#x200d🔬
 * @property string technologist &amp;#x1f9d1&amp;#x200d💻
 * @property string manTechnologist &amp;#x1f468&amp;#x200d💻
 * @property string womanTechnologist &amp;#x1f469&amp;#x200d💻
 * @property string singer &amp;#x1f9d1&amp;#x200d🎤
 * @property string manSinger &amp;#x1f468&amp;#x200d🎤
 * @property string womanSinger &amp;#x1f469&amp;#x200d🎤
 * @property string artist &amp;#x1f9d1&amp;#x200d🎨
 * @property string manArtist &amp;#x1f468&amp;#x200d🎨
 * @property string womanArtist &amp;#x1f469&amp;#x200d🎨
 * @property string pilot &amp;#x1f9d1&amp;#x200d&amp;#x2708️
 * @property string manPilot &amp;#x1f468&amp;#x200d&amp;#x2708️
 * @property string womanPilot &amp;#x1f469&amp;#x200d&amp;#x2708️
 * @property string astronaut &amp;#x1f9d1&amp;#x200d🚀
 * @property string manAstronaut &amp;#x1f468&amp;#x200d🚀
 * @property string womanAstronaut &amp;#x1f469&amp;#x200d🚀
 * @property string firefighter &amp;#x1f9d1&amp;#x200d🚒
 * @property string manFirefighter &amp;#x1f468&amp;#x200d🚒
 * @property string womanFirefighter &amp;#x1f469&amp;#x200d🚒
 * @property string policeOfficer 👮
 * @property string manPoliceOfficer &amp;#x1f46e&amp;#x200d&amp;#x2642️
 * @property string womanPoliceOfficer &amp;#x1f46e&amp;#x200d&amp;#x2640️
 * @property string detective 🕵
 * @property string manDetective &amp;#x1f575&amp;#xfe0f&amp;#x200d&amp;#x2642️
 * @property string womanDetective &amp;#x1f575&amp;#xfe0f&amp;#x200d&amp;#x2640️
 * @property string guard 💂
 * @property string manGuard &amp;#x1f482&amp;#x200d&amp;#x2642️
 * @property string womanGuard &amp;#x1f482&amp;#x200d&amp;#x2640️
 * @property string constructionWorker 👷
 * @property string manConstructionWorker &amp;#x1f477&amp;#x200d&amp;#x2642️
 * @property string womanConstructionWorker &amp;#x1f477&amp;#x200d&amp;#x2640️
 * @property string prince 🤴
 * @property string princess 👸
 * @property string personWearingTurban 👳
 * @property string manWearingTurban &amp;#x1f473&amp;#x200d&amp;#x2642️
 * @property string womanWearingTurban &amp;#x1f473&amp;#x200d&amp;#x2640️
 * @property string manWithSkullcap 👲
 * @property string womanWithHeadscarf 🧕
 * @property string manInTuxedo 🤵
 * @property string brideWithVeil 👰
 * @property string pregnantWoman 🤰
 * @property string breastFeeding 🤱
 * @property string babyAngel 👼
 * @property string santaClaus 🎅
 * @property string mrsClaus 🤶
 * @property string superhero 🦸
 * @property string manSuperhero &amp;#x1f9b8&amp;#x200d&amp;#x2642️
 * @property string womanSuperhero &amp;#x1f9b8&amp;#x200d&amp;#x2640️
 * @property string supervillain 🦹
 * @property string manSupervillain &amp;#x1f9b9&amp;#x200d&amp;#x2642️
 * @property string womanSupervillain &amp;#x1f9b9&amp;#x200d&amp;#x2640️
 * @property string mage 🧙
 * @property string manMage &amp;#x1f9d9&amp;#x200d&amp;#x2642️
 * @property string womanMage &amp;#x1f9d9&amp;#x200d&amp;#x2640️
 * @property string fairy 🧚
 * @property string manFairy &amp;#x1f9da&amp;#x200d&amp;#x2642️
 * @property string womanFairy &amp;#x1f9da&amp;#x200d&amp;#x2640️
 * @property string vampire 🧛
 * @property string manVampire &amp;#x1f9db&amp;#x200d&amp;#x2642️
 * @property string womanVampire &amp;#x1f9db&amp;#x200d&amp;#x2640️
 * @property string merperson 🧜
 * @property string merman &amp;#x1f9dc&amp;#x200d&amp;#x2642️
 * @property string mermaid &amp;#x1f9dc&amp;#x200d&amp;#x2640️
 * @property string elf 🧝
 * @property string manElf &amp;#x1f9dd&amp;#x200d&amp;#x2642️
 * @property string womanElf &amp;#x1f9dd&amp;#x200d&amp;#x2640️
 * @property string genie 🧞
 * @property string manGenie &amp;#x1f9de&amp;#x200d&amp;#x2642️
 * @property string womanGenie &amp;#x1f9de&amp;#x200d&amp;#x2640️
 * @property string zombie 🧟
 * @property string manZombie &amp;#x1f9df&amp;#x200d&amp;#x2642️
 * @property string womanZombie &amp;#x1f9df&amp;#x200d&amp;#x2640️
 * @property string personGettingMassage 💆
 * @property string manGettingMassage &amp;#x1f486&amp;#x200d&amp;#x2642️
 * @property string womanGettingMassage &amp;#x1f486&amp;#x200d&amp;#x2640️
 * @property string personGettingHaircut 💇
 * @property string manGettingHaircut &amp;#x1f487&amp;#x200d&amp;#x2642️
 * @property string womanGettingHaircut &amp;#x1f487&amp;#x200d&amp;#x2640️
 * @property string personWalking 🚶
 * @property string manWalking &amp;#x1f6b6&amp;#x200d&amp;#x2642️
 * @property string womanWalking &amp;#x1f6b6&amp;#x200d&amp;#x2640️
 * @property string personStanding 🧍
 * @property string manStanding &amp;#x1f9cd&amp;#x200d&amp;#x2642️
 * @property string womanStanding &amp;#x1f9cd&amp;#x200d&amp;#x2640️
 * @property string personKneeling 🧎
 * @property string manKneeling &amp;#x1f9ce&amp;#x200d&amp;#x2642️
 * @property string womanKneeling &amp;#x1f9ce&amp;#x200d&amp;#x2640️
 * @property string personWithProbingCane &amp;#x1f9d1&amp;#x200d🦯
 * @property string manWithProbingCane &amp;#x1f468&amp;#x200d🦯
 * @property string womanWithProbingCane &amp;#x1f469&amp;#x200d🦯
 * @property string personInMotorizedWheelchair &amp;#x1f9d1&amp;#x200d🦼
 * @property string manInMotorizedWheelchair &amp;#x1f468&amp;#x200d🦼
 * @property string womanInMotorizedWheelchair &amp;#x1f469&amp;#x200d🦼
 * @property string personInManualWheelchair &amp;#x1f9d1&amp;#x200d🦽
 * @property string manInManualWheelchair &amp;#x1f468&amp;#x200d🦽
 * @property string womanInManualWheelchair &amp;#x1f469&amp;#x200d🦽
 * @property string personRunning 🏃
 * @property string manRunning &amp;#x1f3c3&amp;#x200d&amp;#x2642️
 * @property string womanRunning &amp;#x1f3c3&amp;#x200d&amp;#x2640️
 * @property string womanDancing 💃
 * @property string manDancing 🕺
 * @property string manInSuitLevitating 🕴
 * @property string peopleWithBunnyEars 👯
 * @property string menWithBunnyEars &amp;#x1f46f&amp;#x200d&amp;#x2642️
 * @property string womenWithBunnyEars &amp;#x1f46f&amp;#x200d&amp;#x2640️
 * @property string personInSteamyRoom 🧖
 * @property string manInSteamyRoom &amp;#x1f9d6&amp;#x200d&amp;#x2642️
 * @property string womanInSteamyRoom &amp;#x1f9d6&amp;#x200d&amp;#x2640️
 * @property string personClimbing 🧗
 * @property string manClimbing &amp;#x1f9d7&amp;#x200d&amp;#x2642️
 * @property string womanClimbing &amp;#x1f9d7&amp;#x200d&amp;#x2640️
 * @property string personFencing 🤺
 * @property string horseRacing 🏇
 * @property string skier ⛷
 * @property string snowboarder 🏂
 * @property string personGolfing 🏌
 * @property string manGolfing &amp;#x1f3cc&amp;#xfe0f&amp;#x200d&amp;#x2642️
 * @property string womanGolfing &amp;#x1f3cc&amp;#xfe0f&amp;#x200d&amp;#x2640️
 * @property string personSurfing 🏄
 * @property string manSurfing &amp;#x1f3c4&amp;#x200d&amp;#x2642️
 * @property string womanSurfing &amp;#x1f3c4&amp;#x200d&amp;#x2640️
 * @property string personRowingBoat 🚣
 * @property string manRowingBoat &amp;#x1f6a3&amp;#x200d&amp;#x2642️
 * @property string womanRowingBoat &amp;#x1f6a3&amp;#x200d&amp;#x2640️
 * @property string personSwimming 🏊
 * @property string manSwimming &amp;#x1f3ca&amp;#x200d&amp;#x2642️
 * @property string womanSwimming &amp;#x1f3ca&amp;#x200d&amp;#x2640️
 * @property string personBouncingBall ⛹
 * @property string manBouncingBall &amp;#x26f9&amp;#xfe0f&amp;#x200d&amp;#x2642️
 * @property string womanBouncingBall &amp;#x26f9&amp;#xfe0f&amp;#x200d&amp;#x2640️
 * @property string personLiftingWeights 🏋
 * @property string manLiftingWeights &amp;#x1f3cb&amp;#xfe0f&amp;#x200d&amp;#x2642️
 * @property string womanLiftingWeights &amp;#x1f3cb&amp;#xfe0f&amp;#x200d&amp;#x2640️
 * @property string personBiking 🚴
 * @property string manBiking &amp;#x1f6b4&amp;#x200d&amp;#x2642️
 * @property string womanBiking &amp;#x1f6b4&amp;#x200d&amp;#x2640️
 * @property string personMountainBiking 🚵
 * @property string manMountainBiking &amp;#x1f6b5&amp;#x200d&amp;#x2642️
 * @property string womanMountainBiking &amp;#x1f6b5&amp;#x200d&amp;#x2640️
 * @property string personCartwheeling 🤸
 * @property string manCartwheeling &amp;#x1f938&amp;#x200d&amp;#x2642️
 * @property string womanCartwheeling &amp;#x1f938&amp;#x200d&amp;#x2640️
 * @property string peopleWrestling 🤼
 * @property string menWrestling &amp;#x1f93c&amp;#x200d&amp;#x2642️
 * @property string womenWrestling &amp;#x1f93c&amp;#x200d&amp;#x2640️
 * @property string personPlayingWaterPolo 🤽
 * @property string manPlayingWaterPolo &amp;#x1f93d&amp;#x200d&amp;#x2642️
 * @property string womanPlayingWaterPolo &amp;#x1f93d&amp;#x200d&amp;#x2640️
 * @property string personPlayingHandball 🤾
 * @property string manPlayingHandball &amp;#x1f93e&amp;#x200d&amp;#x2642️
 * @property string womanPlayingHandball &amp;#x1f93e&amp;#x200d&amp;#x2640️
 * @property string personJuggling 🤹
 * @property string manJuggling &amp;#x1f939&amp;#x200d&amp;#x2642️
 * @property string womanJuggling &amp;#x1f939&amp;#x200d&amp;#x2640️
 * @property string personInLotusPosition 🧘
 * @property string manInLotusPosition &amp;#x1f9d8&amp;#x200d&amp;#x2642️
 * @property string womanInLotusPosition &amp;#x1f9d8&amp;#x200d&amp;#x2640️
 * @property string personTakingBath 🛀
 * @property string personInBed 🛌
 * @property string peopleHoldingHands &amp;#x1f9d1&amp;#x200d&amp;#x1f91d&amp;#x200d🧑
 * @property string womenHoldingHands 👭
 * @property string womanAndManHoldingHands 👫
 * @property string menHoldingHands 👬
 * @property string kiss 💏
 * @property string kissWomanMan &amp;#x1f469&amp;#x200d&amp;#x2764&amp;#xfe0f&amp;#x200d&amp;#x1f48b&amp;#x200d👨
 * @property string kissManMan &amp;#x1f468&amp;#x200d&amp;#x2764&amp;#xfe0f&amp;#x200d&amp;#x1f48b&amp;#x200d👨
 * @property string kissWomanWoman &amp;#x1f469&amp;#x200d&amp;#x2764&amp;#xfe0f&amp;#x200d&amp;#x1f48b&amp;#x200d👩
 * @property string coupleWithHeart 💑
 * @property string coupleWithHeartWomanMan &amp;#x1f469&amp;#x200d&amp;#x2764&amp;#xfe0f&amp;#x200d👨
 * @property string coupleWithHeartManMan &amp;#x1f468&amp;#x200d&amp;#x2764&amp;#xfe0f&amp;#x200d👨
 * @property string coupleWithHeartWomanWoman &amp;#x1f469&amp;#x200d&amp;#x2764&amp;#xfe0f&amp;#x200d👩
 * @property string family 👪
 * @property string familyManWomanBoy &amp;#x1f468&amp;#x200d&amp;#x1f469&amp;#x200d👦
 * @property string familyManWomanGirl &amp;#x1f468&amp;#x200d&amp;#x1f469&amp;#x200d👧
 * @property string familyManWomanGirlBoy &amp;#x1f468&amp;#x200d&amp;#x1f469&amp;#x200d&amp;#x1f467&amp;#x200d👦
 * @property string familyManWomanBoyBoy &amp;#x1f468&amp;#x200d&amp;#x1f469&amp;#x200d&amp;#x1f466&amp;#x200d👦
 * @property string familyManWomanGirlGirl &amp;#x1f468&amp;#x200d&amp;#x1f469&amp;#x200d&amp;#x1f467&amp;#x200d👧
 * @property string familyManManBoy &amp;#x1f468&amp;#x200d&amp;#x1f468&amp;#x200d👦
 * @property string familyManManGirl &amp;#x1f468&amp;#x200d&amp;#x1f468&amp;#x200d👧
 * @property string familyManManGirlBoy &amp;#x1f468&amp;#x200d&amp;#x1f468&amp;#x200d&amp;#x1f467&amp;#x200d👦
 * @property string familyManManBoyBoy &amp;#x1f468&amp;#x200d&amp;#x1f468&amp;#x200d&amp;#x1f466&amp;#x200d👦
 * @property string familyManManGirlGirl &amp;#x1f468&amp;#x200d&amp;#x1f468&amp;#x200d&amp;#x1f467&amp;#x200d👧
 * @property string familyWomanWomanBoy &amp;#x1f469&amp;#x200d&amp;#x1f469&amp;#x200d👦
 * @property string familyWomanWomanGirl &amp;#x1f469&amp;#x200d&amp;#x1f469&amp;#x200d👧
 * @property string familyWomanWomanGirlBoy &amp;#x1f469&amp;#x200d&amp;#x1f469&amp;#x200d&amp;#x1f467&amp;#x200d👦
 * @property string familyWomanWomanBoyBoy &amp;#x1f469&amp;#x200d&amp;#x1f469&amp;#x200d&amp;#x1f466&amp;#x200d👦
 * @property string familyWomanWomanGirlGirl &amp;#x1f469&amp;#x200d&amp;#x1f469&amp;#x200d&amp;#x1f467&amp;#x200d👧
 * @property string familyManBoy &amp;#x1f468&amp;#x200d👦
 * @property string familyManBoyBoy &amp;#x1f468&amp;#x200d&amp;#x1f466&amp;#x200d👦
 * @property string familyManGirl &amp;#x1f468&amp;#x200d👧
 * @property string familyManGirlBoy &amp;#x1f468&amp;#x200d&amp;#x1f467&amp;#x200d👦
 * @property string familyManGirlGirl &amp;#x1f468&amp;#x200d&amp;#x1f467&amp;#x200d👧
 * @property string familyWomanBoy &amp;#x1f469&amp;#x200d👦
 * @property string familyWomanBoyBoy &amp;#x1f469&amp;#x200d&amp;#x1f466&amp;#x200d👦
 * @property string familyWomanGirl &amp;#x1f469&amp;#x200d👧
 * @property string familyWomanGirlBoy &amp;#x1f469&amp;#x200d&amp;#x1f467&amp;#x200d👦
 * @property string familyWomanGirlGirl &amp;#x1f469&amp;#x200d&amp;#x1f467&amp;#x200d👧
 * @property string speakingHead 🗣
 * @property string bustInSilhouette 👤
 * @property string bustsInSilhouette 👥
 * @property string footprints 👣
 * @property string redHair 🦰
 * @property string curlyHair 🦱
 * @property string whiteHair 🦳
 * @property string bald 🦲
 * @property string monkeyFace 🐵
 * @property string monkey 🐒
 * @property string gorilla 🦍
 * @property string orangutan 🦧
 * @property string dogFace 🐶
 * @property string dog 🐕
 * @property string guideDog 🦮
 * @property string serviceDog &amp;#x1f415&amp;#x200d🦺
 * @property string poodle 🐩
 * @property string wolf 🐺
 * @property string fox 🦊
 * @property string raccoon 🦝
 * @property string catFace 🐱
 * @property string cat 🐈
 * @property string lion 🦁
 * @property string tigerFace 🐯
 * @property string tiger 🐅
 * @property string leopard 🐆
 * @property string horseFace 🐴
 * @property string horse 🐎
 * @property string unicorn 🦄
 * @property string zebra 🦓
 * @property string deer 🦌
 * @property string cowFace 🐮
 * @property string ox 🐂
 * @property string waterBuffalo 🐃
 * @property string cow 🐄
 * @property string pigFace 🐷
 * @property string pig 🐖
 * @property string boar 🐗
 * @property string pigNose 🐽
 * @property string ram 🐏
 * @property string ewe 🐑
 * @property string goat 🐐
 * @property string camel 🐪
 * @property string twoHumpCamel 🐫
 * @property string llama 🦙
 * @property string giraffe 🦒
 * @property string elephant 🐘
 * @property string rhinoceros 🦏
 * @property string hippopotamus 🦛
 * @property string mouseFace 🐭
 * @property string mouse 🐁
 * @property string rat 🐀
 * @property string hamster 🐹
 * @property string rabbitFace 🐰
 * @property string rabbit 🐇
 * @property string chipmunk 🐿
 * @property string hedgehog 🦔
 * @property string bat 🦇
 * @property string bear 🐻
 * @property string koala 🐨
 * @property string panda 🐼
 * @property string sloth 🦥
 * @property string otter 🦦
 * @property string skunk 🦨
 * @property string kangaroo 🦘
 * @property string badger 🦡
 * @property string pawPrints 🐾
 * @property string turkey 🦃
 * @property string chicken 🐔
 * @property string rooster 🐓
 * @property string hatchingChick 🐣
 * @property string babyChick 🐤
 * @property string frontFacingBabyChick 🐥
 * @property string bird 🐦
 * @property string penguin 🐧
 * @property string dove 🕊
 * @property string eagle 🦅
 * @property string duck 🦆
 * @property string swan 🦢
 * @property string owl 🦉
 * @property string flamingo 🦩
 * @property string peacock 🦚
 * @property string parrot 🦜
 * @property string frog 🐸
 * @property string crocodile 🐊
 * @property string turtle 🐢
 * @property string lizard 🦎
 * @property string snake 🐍
 * @property string dragonFace 🐲
 * @property string dragon 🐉
 * @property string sauropod 🦕
 * @property string tRex 🦖
 * @property string spoutingWhale 🐳
 * @property string whale 🐋
 * @property string dolphin 🐬
 * @property string fish 🐟
 * @property string tropicalFish 🐠
 * @property string blowfish 🐡
 * @property string shark 🦈
 * @property string octopus 🐙
 * @property string spiralShell 🐚
 * @property string snail 🐌
 * @property string butterfly 🦋
 * @property string bug 🐛
 * @property string ant 🐜
 * @property string honeybee 🐝
 * @property string ladyBeetle 🐞
 * @property string cricket 🦗
 * @property string spider 🕷
 * @property string spiderWeb 🕸
 * @property string scorpion 🦂
 * @property string mosquito 🦟
 * @property string microbe 🦠
 * @property string bouquet 💐
 * @property string cherryBlossom 🌸
 * @property string whiteFlower 💮
 * @property string rosette 🏵
 * @property string rose 🌹
 * @property string wiltedFlower 🥀
 * @property string hibiscus 🌺
 * @property string sunflower 🌻
 * @property string blossom 🌼
 * @property string tulip 🌷
 * @property string seedling 🌱
 * @property string evergreenTree 🌲
 * @property string deciduousTree 🌳
 * @property string palmTree 🌴
 * @property string cactus 🌵
 * @property string sheafOfRice 🌾
 * @property string herb 🌿
 * @property string shamrock ☘
 * @property string fourLeafClover 🍀
 * @property string mapleLeaf 🍁
 * @property string fallenLeaf 🍂
 * @property string leafFlutteringInWind 🍃
 * @property string grapes 🍇
 * @property string melon 🍈
 * @property string watermelon 🍉
 * @property string tangerine 🍊
 * @property string lemon 🍋
 * @property string banana 🍌
 * @property string pineapple 🍍
 * @property string mango 🥭
 * @property string redApple 🍎
 * @property string greenApple 🍏
 * @property string pear 🍐
 * @property string peach 🍑
 * @property string cherries 🍒
 * @property string strawberry 🍓
 * @property string kiwiFruit 🥝
 * @property string tomato 🍅
 * @property string coconut 🥥
 * @property string avocado 🥑
 * @property string eggplant 🍆
 * @property string potato 🥔
 * @property string carrot 🥕
 * @property string earOfCorn 🌽
 * @property string hotPepper 🌶
 * @property string cucumber 🥒
 * @property string leafyGreen 🥬
 * @property string broccoli 🥦
 * @property string garlic 🧄
 * @property string onion 🧅
 * @property string mushroom 🍄
 * @property string peanuts 🥜
 * @property string chestnut 🌰
 * @property string bread 🍞
 * @property string croissant 🥐
 * @property string baguetteBread 🥖
 * @property string pretzel 🥨
 * @property string bagel 🥯
 * @property string pancakes 🥞
 * @property string waffle 🧇
 * @property string cheeseWedge 🧀
 * @property string meatOnBone 🍖
 * @property string poultryLeg 🍗
 * @property string cutOfMeat 🥩
 * @property string bacon 🥓
 * @property string hamburger 🍔
 * @property string frenchFries 🍟
 * @property string pizza 🍕
 * @property string hotDog 🌭
 * @property string sandwich 🥪
 * @property string taco 🌮
 * @property string burrito 🌯
 * @property string stuffedFlatbread 🥙
 * @property string falafel 🧆
 * @property string egg 🥚
 * @property string cooking 🍳
 * @property string shallowPanOfFood 🥘
 * @property string potOfFood 🍲
 * @property string bowlWithSpoon 🥣
 * @property string greenSalad 🥗
 * @property string popcorn 🍿
 * @property string butter 🧈
 * @property string salt 🧂
 * @property string cannedFood 🥫
 * @property string bentoBox 🍱
 * @property string riceCracker 🍘
 * @property string riceBall 🍙
 * @property string cookedRice 🍚
 * @property string curryRice 🍛
 * @property string steamingBowl 🍜
 * @property string spaghetti 🍝
 * @property string roastedSweetPotato 🍠
 * @property string oden 🍢
 * @property string sushi 🍣
 * @property string friedShrimp 🍤
 * @property string fishCakeWithSwirl 🍥
 * @property string moonCake 🥮
 * @property string dango 🍡
 * @property string dumpling 🥟
 * @property string fortuneCookie 🥠
 * @property string takeoutBox 🥡
 * @property string crab 🦀
 * @property string lobster 🦞
 * @property string shrimp 🦐
 * @property string squid 🦑
 * @property string oyster 🦪
 * @property string softIceCream 🍦
 * @property string shavedIce 🍧
 * @property string iceCream 🍨
 * @property string doughnut 🍩
 * @property string cookie 🍪
 * @property string birthdayCake 🎂
 * @property string shortcake 🍰
 * @property string cupcake 🧁
 * @property string pie 🥧
 * @property string chocolateBar 🍫
 * @property string candy 🍬
 * @property string lollipop 🍭
 * @property string custard 🍮
 * @property string honeyPot 🍯
 * @property string babyBottle 🍼
 * @property string glassOfMilk 🥛
 * @property string hotBeverage ☕
 * @property string teacupWithoutHandle 🍵
 * @property string sake 🍶
 * @property string bottleWithPoppingCork 🍾
 * @property string wineGlass 🍷
 * @property string cocktailGlass 🍸
 * @property string tropicalDrink 🍹
 * @property string beerMug 🍺
 * @property string clinkingBeerMugs 🍻
 * @property string clinkingGlasses 🥂
 * @property string tumblerGlass 🥃
 * @property string cupWithStraw 🥤
 * @property string beverageBox 🧃
 * @property string mate 🧉
 * @property string ice 🧊
 * @property string chopsticks 🥢
 * @property string forkAndKnifeWithPlate 🍽
 * @property string forkAndKnife 🍴
 * @property string spoon 🥄
 * @property string kitchenKnife 🔪
 * @property string amphora 🏺
 * @property string globeShowingEuropeAfrica 🌍
 * @property string globeShowingAmericas 🌎
 * @property string globeShowingAsiaAustralia 🌏
 * @property string globeWithMeridians 🌐
 * @property string worldMap 🗺
 * @property string mapOfJapan 🗾
 * @property string compass 🧭
 * @property string snowCappedMountain 🏔
 * @property string mountain ⛰
 * @property string volcano 🌋
 * @property string mountFuji 🗻
 * @property string camping 🏕
 * @property string beachWithUmbrella 🏖
 * @property string desert 🏜
 * @property string desertIsland 🏝
 * @property string nationalPark 🏞
 * @property string stadium 🏟
 * @property string classicalBuilding 🏛
 * @property string buildingConstruction 🏗
 * @property string brick 🧱
 * @property string houses 🏘
 * @property string derelictHouse 🏚
 * @property string house 🏠
 * @property string houseWithGarden 🏡
 * @property string officeBuilding 🏢
 * @property string japanesePostOffice 🏣
 * @property string postOffice 🏤
 * @property string hospital 🏥
 * @property string bank 🏦
 * @property string hotel 🏨
 * @property string loveHotel 🏩
 * @property string convenienceStore 🏪
 * @property string school 🏫
 * @property string departmentStore 🏬
 * @property string factory 🏭
 * @property string japaneseCastle 🏯
 * @property string castle 🏰
 * @property string wedding 💒
 * @property string tokyoTower 🗼
 * @property string statueOfLiberty 🗽
 * @property string church ⛪
 * @property string mosque 🕌
 * @property string hinduTemple 🛕
 * @property string synagogue 🕍
 * @property string shintoShrine ⛩
 * @property string kaaba 🕋
 * @property string fountain ⛲
 * @property string tent ⛺
 * @property string foggy 🌁
 * @property string nightWithStars 🌃
 * @property string cityscape 🏙
 * @property string sunriseOverMountains 🌄
 * @property string sunrise 🌅
 * @property string cityscapeAtDusk 🌆
 * @property string sunset 🌇
 * @property string bridgeAtNight 🌉
 * @property string hotSprings ♨
 * @property string carouselHorse 🎠
 * @property string ferrisWheel 🎡
 * @property string rollerCoaster 🎢
 * @property string barberPole 💈
 * @property string circusTent 🎪
 * @property string locomotive 🚂
 * @property string railwayCar 🚃
 * @property string highSpeedTrain 🚄
 * @property string bulletTrain 🚅
 * @property string train 🚆
 * @property string metro 🚇
 * @property string lightRail 🚈
 * @property string station 🚉
 * @property string tram 🚊
 * @property string monorail 🚝
 * @property string mountainRailway 🚞
 * @property string tramCar 🚋
 * @property string bus 🚌
 * @property string oncomingBus 🚍
 * @property string trolleybus 🚎
 * @property string minibus 🚐
 * @property string ambulance 🚑
 * @property string fireEngine 🚒
 * @property string policeCar 🚓
 * @property string oncomingPoliceCar 🚔
 * @property string taxi 🚕
 * @property string oncomingTaxi 🚖
 * @property string automobile 🚗
 * @property string oncomingAutomobile 🚘
 * @property string sportUtilityVehicle 🚙
 * @property string deliveryTruck 🚚
 * @property string articulatedLorry 🚛
 * @property string tractor 🚜
 * @property string racingCar 🏎
 * @property string motorcycle 🏍
 * @property string motorScooter 🛵
 * @property string manualWheelchair 🦽
 * @property string motorizedWheelchair 🦼
 * @property string autoRickshaw 🛺
 * @property string bicycle 🚲
 * @property string kickScooter 🛴
 * @property string skateboard 🛹
 * @property string busStop 🚏
 * @property string motorway 🛣
 * @property string railwayTrack 🛤
 * @property string oilDrum 🛢
 * @property string fuelPump ⛽
 * @property string policeCarLight 🚨
 * @property string horizontalTrafficLight 🚥
 * @property string verticalTrafficLight 🚦
 * @property string stopSign 🛑
 * @property string construction 🚧
 * @property string anchor ⚓
 * @property string sailboat ⛵
 * @property string canoe 🛶
 * @property string speedboat 🚤
 * @property string passengerShip 🛳
 * @property string ferry ⛴
 * @property string motorBoat 🛥
 * @property string ship 🚢
 * @property string airplane ✈
 * @property string smallAirplane 🛩
 * @property string airplaneDeparture 🛫
 * @property string airplaneArrival 🛬
 * @property string parachute 🪂
 * @property string seat 💺
 * @property string helicopter 🚁
 * @property string suspensionRailway 🚟
 * @property string mountainCableway 🚠
 * @property string aerialTramway 🚡
 * @property string satellite 🛰
 * @property string rocket 🚀
 * @property string flyingSaucer 🛸
 * @property string bellhopBell 🛎
 * @property string luggage 🧳
 * @property string hourglassDone ⌛
 * @property string hourglassNotDone ⏳
 * @property string watch ⌚
 * @property string alarmClock ⏰
 * @property string stopwatch ⏱
 * @property string timerClock ⏲
 * @property string mantelpieceClock 🕰
 * @property string twelveOClock 🕛
 * @property string twelveThirty 🕧
 * @property string oneOClock 🕐
 * @property string oneThirty 🕜
 * @property string twoOClock 🕑
 * @property string twoThirty 🕝
 * @property string threeOClock 🕒
 * @property string threeThirty 🕞
 * @property string fourOClock 🕓
 * @property string fourThirty 🕟
 * @property string fiveOClock 🕔
 * @property string fiveThirty 🕠
 * @property string sixOClock 🕕
 * @property string sixThirty 🕡
 * @property string sevenOClock 🕖
 * @property string sevenThirty 🕢
 * @property string eightOClock 🕗
 * @property string eightThirty 🕣
 * @property string nineOClock 🕘
 * @property string nineThirty 🕤
 * @property string tenOClock 🕙
 * @property string tenThirty 🕥
 * @property string elevenOClock 🕚
 * @property string elevenThirty 🕦
 * @property string newMoon 🌑
 * @property string waxingCrescentMoon 🌒
 * @property string firstQuarterMoon 🌓
 * @property string waxingGibbousMoon 🌔
 * @property string fullMoon 🌕
 * @property string waningGibbousMoon 🌖
 * @property string lastQuarterMoon 🌗
 * @property string waningCrescentMoon 🌘
 * @property string crescentMoon 🌙
 * @property string newMoonFace 🌚
 * @property string firstQuarterMoonFace 🌛
 * @property string lastQuarterMoonFace 🌜
 * @property string thermometer 🌡
 * @property string sun ☀
 * @property string fullMoonFace 🌝
 * @property string sunWithFace 🌞
 * @property string ringedPlanet 🪐
 * @property string star ⭐
 * @property string glowingStar 🌟
 * @property string shootingStar 🌠
 * @property string milkyWay 🌌
 * @property string cloud ☁
 * @property string sunBehindCloud ⛅
 * @property string cloudWithLightningAndRain ⛈
 * @property string sunBehindSmallCloud 🌤
 * @property string sunBehindLargeCloud 🌥
 * @property string sunBehindRainCloud 🌦
 * @property string cloudWithRain 🌧
 * @property string cloudWithSnow 🌨
 * @property string cloudWithLightning 🌩
 * @property string tornado 🌪
 * @property string fog 🌫
 * @property string windFace 🌬
 * @property string cyclone 🌀
 * @property string rainbow 🌈
 * @property string closedUmbrella 🌂
 * @property string umbrella ☂
 * @property string umbrellaWithRainDrops ☔
 * @property string umbrellaOnGround ⛱
 * @property string highVoltage ⚡
 * @property string snowflake ❄
 * @property string snowman ☃
 * @property string snowmanWithoutSnow ⛄
 * @property string comet ☄
 * @property string fire 🔥
 * @property string droplet 💧
 * @property string waterWave 🌊
 * @property string jackOLantern 🎃
 * @property string christmasTree 🎄
 * @property string fireworks 🎆
 * @property string sparkler 🎇
 * @property string firecracker 🧨
 * @property string sparkles ✨
 * @property string balloon 🎈
 * @property string partyPopper 🎉
 * @property string confettiBall 🎊
 * @property string tanabataTree 🎋
 * @property string pineDecoration 🎍
 * @property string japaneseDolls 🎎
 * @property string carpStreamer 🎏
 * @property string windChime 🎐
 * @property string moonViewingCeremony 🎑
 * @property string redEnvelope 🧧
 * @property string ribbon 🎀
 * @property string wrappedGift 🎁
 * @property string reminderRibbon 🎗
 * @property string admissionTickets 🎟
 * @property string ticket 🎫
 * @property string militaryMedal 🎖
 * @property string trophy 🏆
 * @property string sportsMedal 🏅
 * @property string firstPlaceMedal 🥇
 * @property string secondPlaceMedal 🥈
 * @property string thirdPlaceMedal 🥉
 * @property string soccerBall ⚽
 * @property string baseball ⚾
 * @property string softball 🥎
 * @property string basketball 🏀
 * @property string volleyball 🏐
 * @property string americanFootball 🏈
 * @property string rugbyFootball 🏉
 * @property string tennis 🎾
 * @property string flyingDisc 🥏
 * @property string bowling 🎳
 * @property string cricketGame 🏏
 * @property string fieldHockey 🏑
 * @property string iceHockey 🏒
 * @property string lacrosse 🥍
 * @property string pingPong 🏓
 * @property string badminton 🏸
 * @property string boxingGlove 🥊
 * @property string martialArtsUniform 🥋
 * @property string goalNet 🥅
 * @property string flagInHole ⛳
 * @property string iceSkate ⛸
 * @property string fishingPole 🎣
 * @property string divingMask 🤿
 * @property string runningShirt 🎽
 * @property string skis 🎿
 * @property string sled 🛷
 * @property string curlingStone 🥌
 * @property string directHit 🎯
 * @property string yoYo 🪀
 * @property string kite 🪁
 * @property string pool8Ball 🎱
 * @property string crystalBall 🔮
 * @property string nazarAmulet 🧿
 * @property string videoGame 🎮
 * @property string joystick 🕹
 * @property string slotMachine 🎰
 * @property string gameDie 🎲
 * @property string puzzlePiece 🧩
 * @property string teddyBear 🧸
 * @property string spadeSuit ♠
 * @property string heartSuit ♥
 * @property string diamondSuit ♦
 * @property string clubSuit ♣
 * @property string chessPawn ♟
 * @property string joker 🃏
 * @property string mahjongRedDragon 🀄
 * @property string flowerPlayingCards 🎴
 * @property string performingArts 🎭
 * @property string framedPicture 🖼
 * @property string artistPalette 🎨
 * @property string thread 🧵
 * @property string yarn 🧶
 * @property string glasses 👓
 * @property string sunglasses 🕶
 * @property string goggles 🥽
 * @property string labCoat 🥼
 * @property string safetyVest 🦺
 * @property string necktie 👔
 * @property string tShirt 👕
 * @property string jeans 👖
 * @property string scarf 🧣
 * @property string gloves 🧤
 * @property string coat 🧥
 * @property string socks 🧦
 * @property string dress 👗
 * @property string kimono 👘
 * @property string sari 🥻
 * @property string onePieceSwimsuit 🩱
 * @property string briefs 🩲
 * @property string shorts 🩳
 * @property string bikini 👙
 * @property string womanSClothes 👚
 * @property string purse 👛
 * @property string handbag 👜
 * @property string clutchBag 👝
 * @property string shoppingBags 🛍
 * @property string backpack 🎒
 * @property string manSShoe 👞
 * @property string runningShoe 👟
 * @property string hikingBoot 🥾
 * @property string flatShoe 🥿
 * @property string highHeeledShoe 👠
 * @property string womanSSandal 👡
 * @property string balletShoes 🩰
 * @property string womanSBoot 👢
 * @property string crown 👑
 * @property string womanSHat 👒
 * @property string topHat 🎩
 * @property string graduationCap 🎓
 * @property string billedCap 🧢
 * @property string rescueWorkerSHelmet ⛑
 * @property string prayerBeads 📿
 * @property string lipstick 💄
 * @property string ring 💍
 * @property string gemStone 💎
 * @property string mutedSpeaker 🔇
 * @property string speakerLowVolume 🔈
 * @property string speakerMediumVolume 🔉
 * @property string speakerHighVolume 🔊
 * @property string loudspeaker 📢
 * @property string megaphone 📣
 * @property string postalHorn 📯
 * @property string bell 🔔
 * @property string bellWithSlash 🔕
 * @property string musicalScore 🎼
 * @property string musicalNote 🎵
 * @property string musicalNotes 🎶
 * @property string studioMicrophone 🎙
 * @property string levelSlider 🎚
 * @property string controlKnobs 🎛
 * @property string microphone 🎤
 * @property string headphone 🎧
 * @property string radio 📻
 * @property string saxophone 🎷
 * @property string guitar 🎸
 * @property string musicalKeyboard 🎹
 * @property string trumpet 🎺
 * @property string violin 🎻
 * @property string banjo 🪕
 * @property string drum 🥁
 * @property string mobilePhone 📱
 * @property string mobilePhoneWithArrow 📲
 * @property string telephone ☎
 * @property string telephoneReceiver 📞
 * @property string pager 📟
 * @property string faxMachine 📠
 * @property string battery 🔋
 * @property string electricPlug 🔌
 * @property string laptop 💻
 * @property string desktopComputer 🖥
 * @property string printer 🖨
 * @property string keyboard ⌨
 * @property string computerMouse 🖱
 * @property string trackball 🖲
 * @property string computerDisk 💽
 * @property string floppyDisk 💾
 * @property string opticalDisk 💿
 * @property string dvd 📀
 * @property string abacus 🧮
 * @property string movieCamera 🎥
 * @property string filmFrames 🎞
 * @property string filmProjector 📽
 * @property string clapperBoard 🎬
 * @property string television 📺
 * @property string camera 📷
 * @property string cameraWithFlash 📸
 * @property string videoCamera 📹
 * @property string videocassette 📼
 * @property string magnifyingGlassTiltedLeft 🔍
 * @property string magnifyingGlassTiltedRight 🔎
 * @property string candle 🕯
 * @property string lightBulb 💡
 * @property string flashlight 🔦
 * @property string redPaperLantern 🏮
 * @property string diyaLamp 🪔
 * @property string notebookWithDecorativeCover 📔
 * @property string closedBook 📕
 * @property string openBook 📖
 * @property string greenBook 📗
 * @property string blueBook 📘
 * @property string orangeBook 📙
 * @property string books 📚
 * @property string notebook 📓
 * @property string ledger 📒
 * @property string pageWithCurl 📃
 * @property string scroll 📜
 * @property string pageFacingUp 📄
 * @property string newspaper 📰
 * @property string rolledUpNewspaper 🗞
 * @property string bookmarkTabs 📑
 * @property string bookmark 🔖
 * @property string label 🏷
 * @property string moneyBag 💰
 * @property string yenBanknote 💴
 * @property string dollarBanknote 💵
 * @property string euroBanknote 💶
 * @property string poundBanknote 💷
 * @property string moneyWithWings 💸
 * @property string creditCard 💳
 * @property string receipt 🧾
 * @property string chartIncreasingWithYen 💹
 * @property string currencyExchange 💱
 * @property string heavyDollarSign 💲
 * @property string envelope ✉
 * @property string eMail 📧
 * @property string incomingEnvelope 📨
 * @property string envelopeWithArrow 📩
 * @property string outboxTray 📤
 * @property string inboxTray 📥
 * @property string package 📦
 * @property string closedMailboxWithRaisedFlag 📫
 * @property string closedMailboxWithLoweredFlag 📪
 * @property string openMailboxWithRaisedFlag 📬
 * @property string openMailboxWithLoweredFlag 📭
 * @property string postbox 📮
 * @property string ballotBoxWithBallot 🗳
 * @property string pencil ✏
 * @property string blackNib ✒
 * @property string fountainPen 🖋
 * @property string pen 🖊
 * @property string paintbrush 🖌
 * @property string crayon 🖍
 * @property string memo 📝
 * @property string briefcase 💼
 * @property string fileFolder 📁
 * @property string openFileFolder 📂
 * @property string cardIndexDividers 🗂
 * @property string calendar 📅
 * @property string tearOffCalendar 📆
 * @property string spiralNotepad 🗒
 * @property string spiralCalendar 🗓
 * @property string cardIndex 📇
 * @property string chartIncreasing 📈
 * @property string chartDecreasing 📉
 * @property string barChart 📊
 * @property string clipboard 📋
 * @property string pushpin 📌
 * @property string roundPushpin 📍
 * @property string paperclip 📎
 * @property string linkedPaperclips 🖇
 * @property string straightRuler 📏
 * @property string triangularRuler 📐
 * @property string scissors ✂
 * @property string cardFileBox 🗃
 * @property string fileCabinet 🗄
 * @property string wastebasket 🗑
 * @property string locked 🔒
 * @property string unlocked 🔓
 * @property string lockedWithPen 🔏
 * @property string lockedWithKey 🔐
 * @property string key 🔑
 * @property string oldKey 🗝
 * @property string hammer 🔨
 * @property string axe 🪓
 * @property string pick ⛏
 * @property string hammerAndPick ⚒
 * @property string hammerAndWrench 🛠
 * @property string dagger 🗡
 * @property string crossedSwords ⚔
 * @property string pistol 🔫
 * @property string bowAndArrow 🏹
 * @property string shield 🛡
 * @property string wrench 🔧
 * @property string nutAndBolt 🔩
 * @property string gear ⚙
 * @property string clamp 🗜
 * @property string balanceScale ⚖
 * @property string probingCane 🦯
 * @property string link 🔗
 * @property string chains ⛓
 * @property string toolbox 🧰
 * @property string magnet 🧲
 * @property string alembic ⚗
 * @property string testTube 🧪
 * @property string petriDish 🧫
 * @property string dna 🧬
 * @property string microscope 🔬
 * @property string telescope 🔭
 * @property string satelliteAntenna 📡
 * @property string syringe 💉
 * @property string dropOfBlood 🩸
 * @property string pill 💊
 * @property string adhesiveBandage 🩹
 * @property string stethoscope 🩺
 * @property string door 🚪
 * @property string bed 🛏
 * @property string couchAndLamp 🛋
 * @property string chair 🪑
 * @property string toilet 🚽
 * @property string shower 🚿
 * @property string bathtub 🛁
 * @property string razor 🪒
 * @property string lotionBottle 🧴
 * @property string safetyPin 🧷
 * @property string broom 🧹
 * @property string basket 🧺
 * @property string rollOfPaper 🧻
 * @property string soap 🧼
 * @property string sponge 🧽
 * @property string fireExtinguisher 🧯
 * @property string shoppingCart 🛒
 * @property string cigarette 🚬
 * @property string coffin ⚰
 * @property string funeralUrn ⚱
 * @property string moai 🗿
 * @property string aTMSign 🏧
 * @property string litterInBinSign 🚮
 * @property string potableWater 🚰
 * @property string wheelchairSymbol ♿
 * @property string menSRoom 🚹
 * @property string womenSRoom 🚺
 * @property string restroom 🚻
 * @property string babySymbol 🚼
 * @property string waterCloset 🚾
 * @property string passportControl 🛂
 * @property string customs 🛃
 * @property string baggageClaim 🛄
 * @property string leftLuggage 🛅
 * @property string warning ⚠
 * @property string childrenCrossing 🚸
 * @property string noEntry ⛔
 * @property string prohibited 🚫
 * @property string noBicycles 🚳
 * @property string noSmoking 🚭
 * @property string noLittering 🚯
 * @property string nonPotableWater 🚱
 * @property string noPedestrians 🚷
 * @property string noMobilePhones 📵
 * @property string noOneUnderEighteen 🔞
 * @property string radioactive ☢
 * @property string biohazard ☣
 * @property string upArrow ⬆
 * @property string upRightArrow ↗
 * @property string rightArrow ➡
 * @property string downRightArrow ↘
 * @property string downArrow ⬇
 * @property string downLeftArrow ↙
 * @property string leftArrow ⬅
 * @property string upLeftArrow ↖
 * @property string upDownArrow ↕
 * @property string leftRightArrow ↔
 * @property string rightArrowCurvingLeft ↩
 * @property string leftArrowCurvingRight ↪
 * @property string rightArrowCurvingUp ⤴
 * @property string rightArrowCurvingDown ⤵
 * @property string clockwiseVerticalArrows 🔃
 * @property string counterclockwiseArrowsButton 🔄
 * @property string bACKArrow 🔙
 * @property string eNDArrow 🔚
 * @property string oNArrow 🔛
 * @property string sOONArrow 🔜
 * @property string tOPArrow 🔝
 * @property string placeOfWorship 🛐
 * @property string atomSymbol ⚛
 * @property string om 🕉
 * @property string starOfDavid ✡
 * @property string wheelOfDharma ☸
 * @property string yinYang ☯
 * @property string latinCross ✝
 * @property string orthodoxCross ☦
 * @property string starAndCrescent ☪
 * @property string peaceSymbol ☮
 * @property string menorah 🕎
 * @property string dottedSixPointedStar 🔯
 * @property string aries ♈
 * @property string taurus ♉
 * @property string gemini ♊
 * @property string cancer ♋
 * @property string leo ♌
 * @property string virgo ♍
 * @property string libra ♎
 * @property string scorpio ♏
 * @property string sagittarius ♐
 * @property string capricorn ♑
 * @property string aquarius ♒
 * @property string pisces ♓
 * @property string ophiuchus ⛎
 * @property string shuffleTracksButton 🔀
 * @property string repeatButton 🔁
 * @property string repeatSingleButton 🔂
 * @property string playButton ▶
 * @property string fastForwardButton ⏩
 * @property string nextTrackButton ⏭
 * @property string playOrPauseButton ⏯
 * @property string reverseButton ◀
 * @property string fastReverseButton ⏪
 * @property string lastTrackButton ⏮
 * @property string upwardsButton 🔼
 * @property string fastUpButton ⏫
 * @property string downwardsButton 🔽
 * @property string fastDownButton ⏬
 * @property string pauseButton ⏸
 * @property string stopButton ⏹
 * @property string recordButton ⏺
 * @property string ejectButton ⏏
 * @property string cinema 🎦
 * @property string dimButton 🔅
 * @property string brightButton 🔆
 * @property string antennaBars 📶
 * @property string vibrationMode 📳
 * @property string mobilePhoneOff 📴
 * @property string femaleSign ♀
 * @property string maleSign ♂
 * @property string medicalSymbol ⚕
 * @property string infinity ♾
 * @property string recyclingSymbol ♻
 * @property string fleurDeLis ⚜
 * @property string tridentEmblem 🔱
 * @property string nameBadge 📛
 * @property string japaneseSymbolForBeginner 🔰
 * @property string hollowRedCircle ⭕
 * @property string checkMarkButton ✅
 * @property string checkBoxWithCheck ☑
 * @property string checkMark ✔
 * @property string multiplicationSign ✖
 * @property string crossMark ❌
 * @property string crossMarkButton ❎
 * @property string plusSign ➕
 * @property string minusSign ➖
 * @property string divisionSign ➗
 * @property string curlyLoop ➰
 * @property string doubleCurlyLoop ➿
 * @property string partAlternationMark 〽
 * @property string eightSpokedAsterisk ✳
 * @property string eightPointedStar ✴
 * @property string sparkle ❇
 * @property string doubleExclamationMark ‼
 * @property string exclamationQuestionMark ⁉
 * @property string questionMark ❓
 * @property string whiteQuestionMark ❔
 * @property string whiteExclamationMark ❕
 * @property string exclamationMark ❗
 * @property string wavyDash 〰
 * @property string copyright ©
 * @property string registered ®
 * @property string tradeMark ™
 * @property string keycapHashtag &amp;#x0023&amp;#xfe0f⃣
 * @property string keycapSnowFlake &amp;#x002a&amp;#xfe0f⃣
 * @property string keycap0 &amp;#x0030&amp;#xfe0f⃣
 * @property string keycap1 &amp;#x0031&amp;#xfe0f⃣
 * @property string keycap2 &amp;#x0032&amp;#xfe0f⃣
 * @property string keycap3 &amp;#x0033&amp;#xfe0f⃣
 * @property string keycap4 &amp;#x0034&amp;#xfe0f⃣
 * @property string keycap5 &amp;#x0035&amp;#xfe0f⃣
 * @property string keycap6 &amp;#x0036&amp;#xfe0f⃣
 * @property string keycap7 &amp;#x0037&amp;#xfe0f⃣
 * @property string keycap8 &amp;#x0038&amp;#xfe0f⃣
 * @property string keycap9 &amp;#x0039&amp;#xfe0f⃣
 * @property string keycap10 🔟
 * @property string inputLatinUppercase 🔠
 * @property string inputLatinLowercase 🔡
 * @property string inputNumbers 🔢
 * @property string inputSymbols 🔣
 * @property string inputLatinLetters 🔤
 * @property string aButtonBloodType 🅰
 * @property string aBButtonBloodType 🆎
 * @property string bButtonBloodType 🅱
 * @property string cLButton 🆑
 * @property string cOOLButton 🆒
 * @property string fREEButton 🆓
 * @property string information ℹ
 * @property string iDButton 🆔
 * @property string circledM Ⓜ
 * @property string nEWButton 🆕
 * @property string nGButton 🆖
 * @property string oButtonBloodType 🅾
 * @property string oKButton 🆗
 * @property string pButton 🅿
 * @property string sOSButton 🆘
 * @property string uPButton 🆙
 * @property string vSButton 🆚
 * @property string japaneseHereButton 🈁
 * @property string japaneseServiceChargeButton 🈂
 * @property string japaneseMonthlyAmountButton 🈷
 * @property string japaneseNotFreeOfChargeButton 🈶
 * @property string japaneseReservedButton 🈯
 * @property string japaneseBargainButton 🉐
 * @property string japaneseDiscountButton 🈹
 * @property string japaneseFreeOfChargeButton 🈚
 * @property string japaneseProhibitedButton 🈲
 * @property string japaneseAcceptableButton 🉑
 * @property string japaneseApplicationButton 🈸
 * @property string japanesePassingGradeButton 🈴
 * @property string japaneseVacancyButton 🈳
 * @property string japaneseCongratulationsButton ㊗
 * @property string japaneseSecretButton ㊙
 * @property string japaneseOpenForBusinessButton 🈺
 * @property string japaneseNoVacancyButton 🈵
 * @property string redCircle 🔴
 * @property string orangeCircle 🟠
 * @property string yellowCircle 🟡
 * @property string greenCircle 🟢
 * @property string blueCircle 🔵
 * @property string purpleCircle 🟣
 * @property string brownCircle 🟤
 * @property string blackCircle ⚫
 * @property string whiteCircle ⚪
 * @property string redSquare 🟥
 * @property string orangeSquare 🟧
 * @property string yellowSquare 🟨
 * @property string greenSquare 🟩
 * @property string blueSquare 🟦
 * @property string purpleSquare 🟪
 * @property string brownSquare 🟫
 * @property string blackLargeSquare ⬛
 * @property string whiteLargeSquare ⬜
 * @property string blackMediumSquare ◼
 * @property string whiteMediumSquare ◻
 * @property string blackMediumSmallSquare ◾
 * @property string whiteMediumSmallSquare ◽
 * @property string blackSmallSquare ▪
 * @property string whiteSmallSquare ▫
 * @property string largeOrangeDiamond 🔶
 * @property string largeBlueDiamond 🔷
 * @property string smallOrangeDiamond 🔸
 * @property string smallBlueDiamond 🔹
 * @property string redTrianglePointedUp 🔺
 * @property string redTrianglePointedDown 🔻
 * @property string diamondWithADot 💠
 * @property string radioButton 🔘
 * @property string whiteSquareButton 🔳
 * @property string blackSquareButton 🔲
 * @property string chequeredFlag 🏁
 * @property string triangularFlag 🚩
 * @property string crossedFlags 🎌
 * @property string blackFlag 🏴
 * @property string whiteFlag 🏳
 * @property string rainbowFlag &amp;#x1f3f3&amp;#xfe0f&amp;#x200d🌈
 * @property string pirateFlag &amp;#x1f3f4&amp;#x200d&amp;#x2620️
 * @property string flagAscensionIsland &amp;#x1f1e6🇨
 * @property string flagAndorra &amp;#x1f1e6🇩
 * @property string flagUnitedArabEmirates &amp;#x1f1e6🇪
 * @property string flagAfghanistan &amp;#x1f1e6🇫
 * @property string flagAntiguaBarbuda &amp;#x1f1e6🇬
 * @property string flagAnguilla &amp;#x1f1e6🇮
 * @property string flagAlbania &amp;#x1f1e6🇱
 * @property string flagArmenia &amp;#x1f1e6🇲
 * @property string flagAngola &amp;#x1f1e6🇴
 * @property string flagAntarctica &amp;#x1f1e6🇶
 * @property string flagArgentina &amp;#x1f1e6🇷
 * @property string flagAmericanSamoa &amp;#x1f1e6🇸
 * @property string flagAustria &amp;#x1f1e6🇹
 * @property string flagAustralia &amp;#x1f1e6🇺
 * @property string flagAruba &amp;#x1f1e6🇼
 * @property string flagLandIslands &amp;#x1f1e6🇽
 * @property string flagAzerbaijan &amp;#x1f1e6🇿
 * @property string flagBosniaHerzegovina &amp;#x1f1e7🇦
 * @property string flagBarbados &amp;#x1f1e7🇧
 * @property string flagBangladesh &amp;#x1f1e7🇩
 * @property string flagBelgium &amp;#x1f1e7🇪
 * @property string flagBurkinaFaso &amp;#x1f1e7🇫
 * @property string flagBulgaria &amp;#x1f1e7🇬
 * @property string flagBahrain &amp;#x1f1e7🇭
 * @property string flagBurundi &amp;#x1f1e7🇮
 * @property string flagBenin &amp;#x1f1e7🇯
 * @property string flagStBarthLemy &amp;#x1f1e7🇱
 * @property string flagBermuda &amp;#x1f1e7🇲
 * @property string flagBrunei &amp;#x1f1e7🇳
 * @property string flagBolivia &amp;#x1f1e7🇴
 * @property string flagCaribbeanNetherlands &amp;#x1f1e7🇶
 * @property string flagBrazil &amp;#x1f1e7🇷
 * @property string flagBahamas &amp;#x1f1e7🇸
 * @property string flagBhutan &amp;#x1f1e7🇹
 * @property string flagBouvetIsland &amp;#x1f1e7🇻
 * @property string flagBotswana &amp;#x1f1e7🇼
 * @property string flagBelarus &amp;#x1f1e7🇾
 * @property string flagBelize &amp;#x1f1e7🇿
 * @property string flagCanada &amp;#x1f1e8🇦
 * @property string flagCocosKeelingIslands &amp;#x1f1e8🇨
 * @property string flagCongoKinshasa &amp;#x1f1e8🇩
 * @property string flagCentralAfricanRepublic &amp;#x1f1e8🇫
 * @property string flagCongoBrazzaville &amp;#x1f1e8🇬
 * @property string flagSwitzerland &amp;#x1f1e8🇭
 * @property string flagCTeDIvoire &amp;#x1f1e8🇮
 * @property string flagCookIslands &amp;#x1f1e8🇰
 * @property string flagChile &amp;#x1f1e8🇱
 * @property string flagCameroon &amp;#x1f1e8🇲
 * @property string flagChina &amp;#x1f1e8🇳
 * @property string flagColombia &amp;#x1f1e8🇴
 * @property string flagClippertonIsland &amp;#x1f1e8🇵
 * @property string flagCostaRica &amp;#x1f1e8🇷
 * @property string flagCuba &amp;#x1f1e8🇺
 * @property string flagCapeVerde &amp;#x1f1e8🇻
 * @property string flagCuraAo &amp;#x1f1e8🇼
 * @property string flagChristmasIsland &amp;#x1f1e8🇽
 * @property string flagCyprus &amp;#x1f1e8🇾
 * @property string flagCzechia &amp;#x1f1e8🇿
 * @property string flagGermany &amp;#x1f1e9🇪
 * @property string flagDiegoGarcia &amp;#x1f1e9🇬
 * @property string flagDjibouti &amp;#x1f1e9🇯
 * @property string flagDenmark &amp;#x1f1e9🇰
 * @property string flagDominica &amp;#x1f1e9🇲
 * @property string flagDominicanRepublic &amp;#x1f1e9🇴
 * @property string flagAlgeria &amp;#x1f1e9🇿
 * @property string flagCeutaMelilla &amp;#x1f1ea🇦
 * @property string flagEcuador &amp;#x1f1ea🇨
 * @property string flagEstonia &amp;#x1f1ea🇪
 * @property string flagEgypt &amp;#x1f1ea🇬
 * @property string flagWesternSahara &amp;#x1f1ea🇭
 * @property string flagEritrea &amp;#x1f1ea🇷
 * @property string flagSpain &amp;#x1f1ea🇸
 * @property string flagEthiopia &amp;#x1f1ea🇹
 * @property string flagEuropeanUnion &amp;#x1f1ea🇺
 * @property string flagFinland &amp;#x1f1eb🇮
 * @property string flagFiji &amp;#x1f1eb🇯
 * @property string flagFalklandIslands &amp;#x1f1eb🇰
 * @property string flagMicronesia &amp;#x1f1eb🇲
 * @property string flagFaroeIslands &amp;#x1f1eb🇴
 * @property string flagFrance &amp;#x1f1eb🇷
 * @property string flagGabon &amp;#x1f1ec🇦
 * @property string flagUnitedKingdom &amp;#x1f1ec🇧
 * @property string flagGrenada &amp;#x1f1ec🇩
 * @property string flagGeorgia &amp;#x1f1ec🇪
 * @property string flagFrenchGuiana &amp;#x1f1ec🇫
 * @property string flagGuernsey &amp;#x1f1ec🇬
 * @property string flagGhana &amp;#x1f1ec🇭
 * @property string flagGibraltar &amp;#x1f1ec🇮
 * @property string flagGreenland &amp;#x1f1ec🇱
 * @property string flagGambia &amp;#x1f1ec🇲
 * @property string flagGuinea &amp;#x1f1ec🇳
 * @property string flagGuadeloupe &amp;#x1f1ec🇵
 * @property string flagEquatorialGuinea &amp;#x1f1ec🇶
 * @property string flagGreece &amp;#x1f1ec🇷
 * @property string flagSouthGeorgiaSouthSandwichIslands &amp;#x1f1ec🇸
 * @property string flagGuatemala &amp;#x1f1ec🇹
 * @property string flagGuam &amp;#x1f1ec🇺
 * @property string flagGuineaBissau &amp;#x1f1ec🇼
 * @property string flagGuyana &amp;#x1f1ec🇾
 * @property string flagHongKongSARChina &amp;#x1f1ed🇰
 * @property string flagHeardMcDonaldIslands &amp;#x1f1ed🇲
 * @property string flagHonduras &amp;#x1f1ed🇳
 * @property string flagCroatia &amp;#x1f1ed🇷
 * @property string flagHaiti &amp;#x1f1ed🇹
 * @property string flagHungary &amp;#x1f1ed🇺
 * @property string flagCanaryIslands &amp;#x1f1ee🇨
 * @property string flagIndonesia &amp;#x1f1ee🇩
 * @property string flagIreland &amp;#x1f1ee🇪
 * @property string flagIsrael &amp;#x1f1ee🇱
 * @property string flagIsleOfMan &amp;#x1f1ee🇲
 * @property string flagIndia &amp;#x1f1ee🇳
 * @property string flagBritishIndianOceanTerritory &amp;#x1f1ee🇴
 * @property string flagIraq &amp;#x1f1ee🇶
 * @property string flagIran &amp;#x1f1ee🇷
 * @property string flagIceland &amp;#x1f1ee🇸
 * @property string flagItaly &amp;#x1f1ee🇹
 * @property string flagJersey &amp;#x1f1ef🇪
 * @property string flagJamaica &amp;#x1f1ef🇲
 * @property string flagJordan &amp;#x1f1ef🇴
 * @property string flagJapan &amp;#x1f1ef🇵
 * @property string flagKenya &amp;#x1f1f0🇪
 * @property string flagKyrgyzstan &amp;#x1f1f0🇬
 * @property string flagCambodia &amp;#x1f1f0🇭
 * @property string flagKiribati &amp;#x1f1f0🇮
 * @property string flagComoros &amp;#x1f1f0🇲
 * @property string flagStKittsNevis &amp;#x1f1f0🇳
 * @property string flagNorthKorea &amp;#x1f1f0🇵
 * @property string flagSouthKorea &amp;#x1f1f0🇷
 * @property string flagKuwait &amp;#x1f1f0🇼
 * @property string flagCaymanIslands &amp;#x1f1f0🇾
 * @property string flagKazakhstan &amp;#x1f1f0🇿
 * @property string flagLaos &amp;#x1f1f1🇦
 * @property string flagLebanon &amp;#x1f1f1🇧
 * @property string flagStLucia &amp;#x1f1f1🇨
 * @property string flagLiechtenstein &amp;#x1f1f1🇮
 * @property string flagSriLanka &amp;#x1f1f1🇰
 * @property string flagLiberia &amp;#x1f1f1🇷
 * @property string flagLesotho &amp;#x1f1f1🇸
 * @property string flagLithuania &amp;#x1f1f1🇹
 * @property string flagLuxembourg &amp;#x1f1f1🇺
 * @property string flagLatvia &amp;#x1f1f1🇻
 * @property string flagLibya &amp;#x1f1f1🇾
 * @property string flagMorocco &amp;#x1f1f2🇦
 * @property string flagMonaco &amp;#x1f1f2🇨
 * @property string flagMoldova &amp;#x1f1f2🇩
 * @property string flagMontenegro &amp;#x1f1f2🇪
 * @property string flagStMartin &amp;#x1f1f2🇫
 * @property string flagMadagascar &amp;#x1f1f2🇬
 * @property string flagMarshallIslands &amp;#x1f1f2🇭
 * @property string flagNorthMacedonia &amp;#x1f1f2🇰
 * @property string flagMali &amp;#x1f1f2🇱
 * @property string flagMyanmarBurma &amp;#x1f1f2🇲
 * @property string flagMongolia &amp;#x1f1f2🇳
 * @property string flagMacaoSARChina &amp;#x1f1f2🇴
 * @property string flagNorthernMarianaIslands &amp;#x1f1f2🇵
 * @property string flagMartinique &amp;#x1f1f2🇶
 * @property string flagMauritania &amp;#x1f1f2🇷
 * @property string flagMontserrat &amp;#x1f1f2🇸
 * @property string flagMalta &amp;#x1f1f2🇹
 * @property string flagMauritius &amp;#x1f1f2🇺
 * @property string flagMaldives &amp;#x1f1f2🇻
 * @property string flagMalawi &amp;#x1f1f2🇼
 * @property string flagMexico &amp;#x1f1f2🇽
 * @property string flagMalaysia &amp;#x1f1f2🇾
 * @property string flagMozambique &amp;#x1f1f2🇿
 * @property string flagNamibia &amp;#x1f1f3🇦
 * @property string flagNewCaledonia &amp;#x1f1f3🇨
 * @property string flagNiger &amp;#x1f1f3🇪
 * @property string flagNorfolkIsland &amp;#x1f1f3🇫
 * @property string flagNigeria &amp;#x1f1f3🇬
 * @property string flagNicaragua &amp;#x1f1f3🇮
 * @property string flagNetherlands &amp;#x1f1f3🇱
 * @property string flagNorway &amp;#x1f1f3🇴
 * @property string flagNepal &amp;#x1f1f3🇵
 * @property string flagNauru &amp;#x1f1f3🇷
 * @property string flagNiue &amp;#x1f1f3🇺
 * @property string flagNewZealand &amp;#x1f1f3🇿
 * @property string flagOman &amp;#x1f1f4🇲
 * @property string flagPanama &amp;#x1f1f5🇦
 * @property string flagPeru &amp;#x1f1f5🇪
 * @property string flagFrenchPolynesia &amp;#x1f1f5🇫
 * @property string flagPapuaNewGuinea &amp;#x1f1f5🇬
 * @property string flagPhilippines &amp;#x1f1f5🇭
 * @property string flagPakistan &amp;#x1f1f5🇰
 * @property string flagPoland &amp;#x1f1f5🇱
 * @property string flagStPierreMiquelon &amp;#x1f1f5🇲
 * @property string flagPitcairnIslands &amp;#x1f1f5🇳
 * @property string flagPuertoRico &amp;#x1f1f5🇷
 * @property string flagPalestinianTerritories &amp;#x1f1f5🇸
 * @property string flagPortugal &amp;#x1f1f5🇹
 * @property string flagPalau &amp;#x1f1f5🇼
 * @property string flagParaguay &amp;#x1f1f5🇾
 * @property string flagQatar &amp;#x1f1f6🇦
 * @property string flagRUnion &amp;#x1f1f7🇪
 * @property string flagRomania &amp;#x1f1f7🇴
 * @property string flagSerbia &amp;#x1f1f7🇸
 * @property string flagRussia &amp;#x1f1f7🇺
 * @property string flagRwanda &amp;#x1f1f7🇼
 * @property string flagSaudiArabia &amp;#x1f1f8🇦
 * @property string flagSolomonIslands &amp;#x1f1f8🇧
 * @property string flagSeychelles &amp;#x1f1f8🇨
 * @property string flagSudan &amp;#x1f1f8🇩
 * @property string flagSweden &amp;#x1f1f8🇪
 * @property string flagSingapore &amp;#x1f1f8🇬
 * @property string flagStHelena &amp;#x1f1f8🇭
 * @property string flagSlovenia &amp;#x1f1f8🇮
 * @property string flagSvalbardJanMayen &amp;#x1f1f8🇯
 * @property string flagSlovakia &amp;#x1f1f8🇰
 * @property string flagSierraLeone &amp;#x1f1f8🇱
 * @property string flagSanMarino &amp;#x1f1f8🇲
 * @property string flagSenegal &amp;#x1f1f8🇳
 * @property string flagSomalia &amp;#x1f1f8🇴
 * @property string flagSuriname &amp;#x1f1f8🇷
 * @property string flagSouthSudan &amp;#x1f1f8🇸
 * @property string flagSOTomPrNcipe &amp;#x1f1f8🇹
 * @property string flagElSalvador &amp;#x1f1f8🇻
 * @property string flagSintMaarten &amp;#x1f1f8🇽
 * @property string flagSyria &amp;#x1f1f8🇾
 * @property string flagEswatini &amp;#x1f1f8🇿
 * @property string flagTristanDaCunha &amp;#x1f1f9🇦
 * @property string flagTurksCaicosIslands &amp;#x1f1f9🇨
 * @property string flagChad &amp;#x1f1f9🇩
 * @property string flagFrenchSouthernTerritories &amp;#x1f1f9🇫
 * @property string flagTogo &amp;#x1f1f9🇬
 * @property string flagThailand &amp;#x1f1f9🇭
 * @property string flagTajikistan &amp;#x1f1f9🇯
 * @property string flagTokelau &amp;#x1f1f9🇰
 * @property string flagTimorLeste &amp;#x1f1f9🇱
 * @property string flagTurkmenistan &amp;#x1f1f9🇲
 * @property string flagTunisia &amp;#x1f1f9🇳
 * @property string flagTonga &amp;#x1f1f9🇴
 * @property string flagTurkey &amp;#x1f1f9🇷
 * @property string flagTrinidadTobago &amp;#x1f1f9🇹
 * @property string flagTuvalu &amp;#x1f1f9🇻
 * @property string flagTaiwan &amp;#x1f1f9🇼
 * @property string flagTanzania &amp;#x1f1f9🇿
 * @property string flagUkraine &amp;#x1f1fa🇦
 * @property string flagUganda &amp;#x1f1fa🇬
 * @property string flagUSOutlyingIslands &amp;#x1f1fa🇲
 * @property string flagUnitedNations &amp;#x1f1fa🇳
 * @property string flagUnitedStates &amp;#x1f1fa🇸
 * @property string flagUruguay &amp;#x1f1fa🇾
 * @property string flagUzbekistan &amp;#x1f1fa🇿
 * @property string flagVaticanCity &amp;#x1f1fb🇦
 * @property string flagStVincentGrenadines &amp;#x1f1fb🇨
 * @property string flagVenezuela &amp;#x1f1fb🇪
 * @property string flagBritishVirginIslands &amp;#x1f1fb🇬
 * @property string flagUSVirginIslands &amp;#x1f1fb🇮
 * @property string flagVietnam &amp;#x1f1fb🇳
 * @property string flagVanuatu &amp;#x1f1fb🇺
 * @property string flagWallisFutuna &amp;#x1f1fc🇫
 * @property string flagSamoa &amp;#x1f1fc🇸
 * @property string flagKosovo &amp;#x1f1fd🇰
 * @property string flagYemen &amp;#x1f1fe🇪
 * @property string flagMayotte &amp;#x1f1fe🇹
 * @property string flagSouthAfrica &amp;#x1f1ff🇦
 * @property string flagZambia &amp;#x1f1ff🇲
 * @property string flagZimbabwe &amp;#x1f1ff🇼
 * @property string flagEngland &amp;#x1f3f4&amp;#xe0067&amp;#xe0062&amp;#xe0065&amp;#xe006e&amp;#xe0067󠁿
 * @property string flagScotland &amp;#x1f3f4&amp;#xe0067&amp;#xe0062&amp;#xe0073&amp;#xe0063&amp;#xe0074󠁿
 * @property string flagWales &amp;#x1f3f4&amp;#xe0067&amp;#xe0062&amp;#xe0077&amp;#xe006c&amp;#xe0073󠁿
 */
class AllEmoji
{

}