<?php

namespace TolgaKaragol\Emoji\Traits\Sub\Flags;

/**
 * Trait CountryFlagTrait
 * @package TolgaKaragol\Emoji\Traits\Sub\Flags\CountryFlagTrait
 *
 * @property string flagAscensionIsland &amp;#x1f1e6🇨
 * @property string flagAndorra &amp;#x1f1e6🇩
 * @property string flagUnitedArabEmirates &amp;#x1f1e6🇪
 * @property string flagAfghanistan &amp;#x1f1e6🇫
 * @property string flagAntiguaBarbuda &amp;#x1f1e6🇬
 * @property string flagAnguilla &amp;#x1f1e6🇮
 * @property string flagAlbania &amp;#x1f1e6🇱
 * @property string flagArmenia &amp;#x1f1e6🇲
 * @property string flagAngola &amp;#x1f1e6🇴
 * @property string flagAntarctica &amp;#x1f1e6🇶
 * @property string flagArgentina &amp;#x1f1e6🇷
 * @property string flagAmericanSamoa &amp;#x1f1e6🇸
 * @property string flagAustria &amp;#x1f1e6🇹
 * @property string flagAustralia &amp;#x1f1e6🇺
 * @property string flagAruba &amp;#x1f1e6🇼
 * @property string flagLandIslands &amp;#x1f1e6🇽
 * @property string flagAzerbaijan &amp;#x1f1e6🇿
 * @property string flagBosniaHerzegovina &amp;#x1f1e7🇦
 * @property string flagBarbados &amp;#x1f1e7🇧
 * @property string flagBangladesh &amp;#x1f1e7🇩
 * @property string flagBelgium &amp;#x1f1e7🇪
 * @property string flagBurkinaFaso &amp;#x1f1e7🇫
 * @property string flagBulgaria &amp;#x1f1e7🇬
 * @property string flagBahrain &amp;#x1f1e7🇭
 * @property string flagBurundi &amp;#x1f1e7🇮
 * @property string flagBenin &amp;#x1f1e7🇯
 * @property string flagStBarthLemy &amp;#x1f1e7🇱
 * @property string flagBermuda &amp;#x1f1e7🇲
 * @property string flagBrunei &amp;#x1f1e7🇳
 * @property string flagBolivia &amp;#x1f1e7🇴
 * @property string flagCaribbeanNetherlands &amp;#x1f1e7🇶
 * @property string flagBrazil &amp;#x1f1e7🇷
 * @property string flagBahamas &amp;#x1f1e7🇸
 * @property string flagBhutan &amp;#x1f1e7🇹
 * @property string flagBouvetIsland &amp;#x1f1e7🇻
 * @property string flagBotswana &amp;#x1f1e7🇼
 * @property string flagBelarus &amp;#x1f1e7🇾
 * @property string flagBelize &amp;#x1f1e7🇿
 * @property string flagCanada &amp;#x1f1e8🇦
 * @property string flagCocosKeelingIslands &amp;#x1f1e8🇨
 * @property string flagCongoKinshasa &amp;#x1f1e8🇩
 * @property string flagCentralAfricanRepublic &amp;#x1f1e8🇫
 * @property string flagCongoBrazzaville &amp;#x1f1e8🇬
 * @property string flagSwitzerland &amp;#x1f1e8🇭
 * @property string flagCTeDIvoire &amp;#x1f1e8🇮
 * @property string flagCookIslands &amp;#x1f1e8🇰
 * @property string flagChile &amp;#x1f1e8🇱
 * @property string flagCameroon &amp;#x1f1e8🇲
 * @property string flagChina &amp;#x1f1e8🇳
 * @property string flagColombia &amp;#x1f1e8🇴
 * @property string flagClippertonIsland &amp;#x1f1e8🇵
 * @property string flagCostaRica &amp;#x1f1e8🇷
 * @property string flagCuba &amp;#x1f1e8🇺
 * @property string flagCapeVerde &amp;#x1f1e8🇻
 * @property string flagCuraAo &amp;#x1f1e8🇼
 * @property string flagChristmasIsland &amp;#x1f1e8🇽
 * @property string flagCyprus &amp;#x1f1e8🇾
 * @property string flagCzechia &amp;#x1f1e8🇿
 * @property string flagGermany &amp;#x1f1e9🇪
 * @property string flagDiegoGarcia &amp;#x1f1e9🇬
 * @property string flagDjibouti &amp;#x1f1e9🇯
 * @property string flagDenmark &amp;#x1f1e9🇰
 * @property string flagDominica &amp;#x1f1e9🇲
 * @property string flagDominicanRepublic &amp;#x1f1e9🇴
 * @property string flagAlgeria &amp;#x1f1e9🇿
 * @property string flagCeutaMelilla &amp;#x1f1ea🇦
 * @property string flagEcuador &amp;#x1f1ea🇨
 * @property string flagEstonia &amp;#x1f1ea🇪
 * @property string flagEgypt &amp;#x1f1ea🇬
 * @property string flagWesternSahara &amp;#x1f1ea🇭
 * @property string flagEritrea &amp;#x1f1ea🇷
 * @property string flagSpain &amp;#x1f1ea🇸
 * @property string flagEthiopia &amp;#x1f1ea🇹
 * @property string flagEuropeanUnion &amp;#x1f1ea🇺
 * @property string flagFinland &amp;#x1f1eb🇮
 * @property string flagFiji &amp;#x1f1eb🇯
 * @property string flagFalklandIslands &amp;#x1f1eb🇰
 * @property string flagMicronesia &amp;#x1f1eb🇲
 * @property string flagFaroeIslands &amp;#x1f1eb🇴
 * @property string flagFrance &amp;#x1f1eb🇷
 * @property string flagGabon &amp;#x1f1ec🇦
 * @property string flagUnitedKingdom &amp;#x1f1ec🇧
 * @property string flagGrenada &amp;#x1f1ec🇩
 * @property string flagGeorgia &amp;#x1f1ec🇪
 * @property string flagFrenchGuiana &amp;#x1f1ec🇫
 * @property string flagGuernsey &amp;#x1f1ec🇬
 * @property string flagGhana &amp;#x1f1ec🇭
 * @property string flagGibraltar &amp;#x1f1ec🇮
 * @property string flagGreenland &amp;#x1f1ec🇱
 * @property string flagGambia &amp;#x1f1ec🇲
 * @property string flagGuinea &amp;#x1f1ec🇳
 * @property string flagGuadeloupe &amp;#x1f1ec🇵
 * @property string flagEquatorialGuinea &amp;#x1f1ec🇶
 * @property string flagGreece &amp;#x1f1ec🇷
 * @property string flagSouthGeorgiaSouthSandwichIslands &amp;#x1f1ec🇸
 * @property string flagGuatemala &amp;#x1f1ec🇹
 * @property string flagGuam &amp;#x1f1ec🇺
 * @property string flagGuineaBissau &amp;#x1f1ec🇼
 * @property string flagGuyana &amp;#x1f1ec🇾
 * @property string flagHongKongSARChina &amp;#x1f1ed🇰
 * @property string flagHeardMcDonaldIslands &amp;#x1f1ed🇲
 * @property string flagHonduras &amp;#x1f1ed🇳
 * @property string flagCroatia &amp;#x1f1ed🇷
 * @property string flagHaiti &amp;#x1f1ed🇹
 * @property string flagHungary &amp;#x1f1ed🇺
 * @property string flagCanaryIslands &amp;#x1f1ee🇨
 * @property string flagIndonesia &amp;#x1f1ee🇩
 * @property string flagIreland &amp;#x1f1ee🇪
 * @property string flagIsrael &amp;#x1f1ee🇱
 * @property string flagIsleOfMan &amp;#x1f1ee🇲
 * @property string flagIndia &amp;#x1f1ee🇳
 * @property string flagBritishIndianOceanTerritory &amp;#x1f1ee🇴
 * @property string flagIraq &amp;#x1f1ee🇶
 * @property string flagIran &amp;#x1f1ee🇷
 * @property string flagIceland &amp;#x1f1ee🇸
 * @property string flagItaly &amp;#x1f1ee🇹
 * @property string flagJersey &amp;#x1f1ef🇪
 * @property string flagJamaica &amp;#x1f1ef🇲
 * @property string flagJordan &amp;#x1f1ef🇴
 * @property string flagJapan &amp;#x1f1ef🇵
 * @property string flagKenya &amp;#x1f1f0🇪
 * @property string flagKyrgyzstan &amp;#x1f1f0🇬
 * @property string flagCambodia &amp;#x1f1f0🇭
 * @property string flagKiribati &amp;#x1f1f0🇮
 * @property string flagComoros &amp;#x1f1f0🇲
 * @property string flagStKittsNevis &amp;#x1f1f0🇳
 * @property string flagNorthKorea &amp;#x1f1f0🇵
 * @property string flagSouthKorea &amp;#x1f1f0🇷
 * @property string flagKuwait &amp;#x1f1f0🇼
 * @property string flagCaymanIslands &amp;#x1f1f0🇾
 * @property string flagKazakhstan &amp;#x1f1f0🇿
 * @property string flagLaos &amp;#x1f1f1🇦
 * @property string flagLebanon &amp;#x1f1f1🇧
 * @property string flagStLucia &amp;#x1f1f1🇨
 * @property string flagLiechtenstein &amp;#x1f1f1🇮
 * @property string flagSriLanka &amp;#x1f1f1🇰
 * @property string flagLiberia &amp;#x1f1f1🇷
 * @property string flagLesotho &amp;#x1f1f1🇸
 * @property string flagLithuania &amp;#x1f1f1🇹
 * @property string flagLuxembourg &amp;#x1f1f1🇺
 * @property string flagLatvia &amp;#x1f1f1🇻
 * @property string flagLibya &amp;#x1f1f1🇾
 * @property string flagMorocco &amp;#x1f1f2🇦
 * @property string flagMonaco &amp;#x1f1f2🇨
 * @property string flagMoldova &amp;#x1f1f2🇩
 * @property string flagMontenegro &amp;#x1f1f2🇪
 * @property string flagStMartin &amp;#x1f1f2🇫
 * @property string flagMadagascar &amp;#x1f1f2🇬
 * @property string flagMarshallIslands &amp;#x1f1f2🇭
 * @property string flagNorthMacedonia &amp;#x1f1f2🇰
 * @property string flagMali &amp;#x1f1f2🇱
 * @property string flagMyanmarBurma &amp;#x1f1f2🇲
 * @property string flagMongolia &amp;#x1f1f2🇳
 * @property string flagMacaoSARChina &amp;#x1f1f2🇴
 * @property string flagNorthernMarianaIslands &amp;#x1f1f2🇵
 * @property string flagMartinique &amp;#x1f1f2🇶
 * @property string flagMauritania &amp;#x1f1f2🇷
 * @property string flagMontserrat &amp;#x1f1f2🇸
 * @property string flagMalta &amp;#x1f1f2🇹
 * @property string flagMauritius &amp;#x1f1f2🇺
 * @property string flagMaldives &amp;#x1f1f2🇻
 * @property string flagMalawi &amp;#x1f1f2🇼
 * @property string flagMexico &amp;#x1f1f2🇽
 * @property string flagMalaysia &amp;#x1f1f2🇾
 * @property string flagMozambique &amp;#x1f1f2🇿
 * @property string flagNamibia &amp;#x1f1f3🇦
 * @property string flagNewCaledonia &amp;#x1f1f3🇨
 * @property string flagNiger &amp;#x1f1f3🇪
 * @property string flagNorfolkIsland &amp;#x1f1f3🇫
 * @property string flagNigeria &amp;#x1f1f3🇬
 * @property string flagNicaragua &amp;#x1f1f3🇮
 * @property string flagNetherlands &amp;#x1f1f3🇱
 * @property string flagNorway &amp;#x1f1f3🇴
 * @property string flagNepal &amp;#x1f1f3🇵
 * @property string flagNauru &amp;#x1f1f3🇷
 * @property string flagNiue &amp;#x1f1f3🇺
 * @property string flagNewZealand &amp;#x1f1f3🇿
 * @property string flagOman &amp;#x1f1f4🇲
 * @property string flagPanama &amp;#x1f1f5🇦
 * @property string flagPeru &amp;#x1f1f5🇪
 * @property string flagFrenchPolynesia &amp;#x1f1f5🇫
 * @property string flagPapuaNewGuinea &amp;#x1f1f5🇬
 * @property string flagPhilippines &amp;#x1f1f5🇭
 * @property string flagPakistan &amp;#x1f1f5🇰
 * @property string flagPoland &amp;#x1f1f5🇱
 * @property string flagStPierreMiquelon &amp;#x1f1f5🇲
 * @property string flagPitcairnIslands &amp;#x1f1f5🇳
 * @property string flagPuertoRico &amp;#x1f1f5🇷
 * @property string flagPalestinianTerritories &amp;#x1f1f5🇸
 * @property string flagPortugal &amp;#x1f1f5🇹
 * @property string flagPalau &amp;#x1f1f5🇼
 * @property string flagParaguay &amp;#x1f1f5🇾
 * @property string flagQatar &amp;#x1f1f6🇦
 * @property string flagRUnion &amp;#x1f1f7🇪
 * @property string flagRomania &amp;#x1f1f7🇴
 * @property string flagSerbia &amp;#x1f1f7🇸
 * @property string flagRussia &amp;#x1f1f7🇺
 * @property string flagRwanda &amp;#x1f1f7🇼
 * @property string flagSaudiArabia &amp;#x1f1f8🇦
 * @property string flagSolomonIslands &amp;#x1f1f8🇧
 * @property string flagSeychelles &amp;#x1f1f8🇨
 * @property string flagSudan &amp;#x1f1f8🇩
 * @property string flagSweden &amp;#x1f1f8🇪
 * @property string flagSingapore &amp;#x1f1f8🇬
 * @property string flagStHelena &amp;#x1f1f8🇭
 * @property string flagSlovenia &amp;#x1f1f8🇮
 * @property string flagSvalbardJanMayen &amp;#x1f1f8🇯
 * @property string flagSlovakia &amp;#x1f1f8🇰
 * @property string flagSierraLeone &amp;#x1f1f8🇱
 * @property string flagSanMarino &amp;#x1f1f8🇲
 * @property string flagSenegal &amp;#x1f1f8🇳
 * @property string flagSomalia &amp;#x1f1f8🇴
 * @property string flagSuriname &amp;#x1f1f8🇷
 * @property string flagSouthSudan &amp;#x1f1f8🇸
 * @property string flagSOTomPrNcipe &amp;#x1f1f8🇹
 * @property string flagElSalvador &amp;#x1f1f8🇻
 * @property string flagSintMaarten &amp;#x1f1f8🇽
 * @property string flagSyria &amp;#x1f1f8🇾
 * @property string flagEswatini &amp;#x1f1f8🇿
 * @property string flagTristanDaCunha &amp;#x1f1f9🇦
 * @property string flagTurksCaicosIslands &amp;#x1f1f9🇨
 * @property string flagChad &amp;#x1f1f9🇩
 * @property string flagFrenchSouthernTerritories &amp;#x1f1f9🇫
 * @property string flagTogo &amp;#x1f1f9🇬
 * @property string flagThailand &amp;#x1f1f9🇭
 * @property string flagTajikistan &amp;#x1f1f9🇯
 * @property string flagTokelau &amp;#x1f1f9🇰
 * @property string flagTimorLeste &amp;#x1f1f9🇱
 * @property string flagTurkmenistan &amp;#x1f1f9🇲
 * @property string flagTunisia &amp;#x1f1f9🇳
 * @property string flagTonga &amp;#x1f1f9🇴
 * @property string flagTurkey &amp;#x1f1f9🇷
 * @property string flagTrinidadTobago &amp;#x1f1f9🇹
 * @property string flagTuvalu &amp;#x1f1f9🇻
 * @property string flagTaiwan &amp;#x1f1f9🇼
 * @property string flagTanzania &amp;#x1f1f9🇿
 * @property string flagUkraine &amp;#x1f1fa🇦
 * @property string flagUganda &amp;#x1f1fa🇬
 * @property string flagUSOutlyingIslands &amp;#x1f1fa🇲
 * @property string flagUnitedNations &amp;#x1f1fa🇳
 * @property string flagUnitedStates &amp;#x1f1fa🇸
 * @property string flagUruguay &amp;#x1f1fa🇾
 * @property string flagUzbekistan &amp;#x1f1fa🇿
 * @property string flagVaticanCity &amp;#x1f1fb🇦
 * @property string flagStVincentGrenadines &amp;#x1f1fb🇨
 * @property string flagVenezuela &amp;#x1f1fb🇪
 * @property string flagBritishVirginIslands &amp;#x1f1fb🇬
 * @property string flagUSVirginIslands &amp;#x1f1fb🇮
 * @property string flagVietnam &amp;#x1f1fb🇳
 * @property string flagVanuatu &amp;#x1f1fb🇺
 * @property string flagWallisFutuna &amp;#x1f1fc🇫
 * @property string flagSamoa &amp;#x1f1fc🇸
 * @property string flagKosovo &amp;#x1f1fd🇰
 * @property string flagYemen &amp;#x1f1fe🇪
 * @property string flagMayotte &amp;#x1f1fe🇹
 * @property string flagSouthAfrica &amp;#x1f1ff🇦
 * @property string flagZambia &amp;#x1f1ff🇲
 * @property string flagZimbabwe &amp;#x1f1ff🇼
 */
trait CountryFlagTrait
{
    protected static $flagAscensionIsland = '&#x1f1e6&#x1f1e8;';
    protected static $flagAndorra = '&#x1f1e6&#x1f1e9;';
    protected static $flagUnitedArabEmirates = '&#x1f1e6&#x1f1ea;';
    protected static $flagAfghanistan = '&#x1f1e6&#x1f1eb;';
    protected static $flagAntiguaBarbuda = '&#x1f1e6&#x1f1ec;';
    protected static $flagAnguilla = '&#x1f1e6&#x1f1ee;';
    protected static $flagAlbania = '&#x1f1e6&#x1f1f1;';
    protected static $flagArmenia = '&#x1f1e6&#x1f1f2;';
    protected static $flagAngola = '&#x1f1e6&#x1f1f4;';
    protected static $flagAntarctica = '&#x1f1e6&#x1f1f6;';
    protected static $flagArgentina = '&#x1f1e6&#x1f1f7;';
    protected static $flagAmericanSamoa = '&#x1f1e6&#x1f1f8;';
    protected static $flagAustria = '&#x1f1e6&#x1f1f9;';
    protected static $flagAustralia = '&#x1f1e6&#x1f1fa;';
    protected static $flagAruba = '&#x1f1e6&#x1f1fc;';
    protected static $flagLandIslands = '&#x1f1e6&#x1f1fd;';
    protected static $flagAzerbaijan = '&#x1f1e6&#x1f1ff;';
    protected static $flagBosniaHerzegovina = '&#x1f1e7&#x1f1e6;';
    protected static $flagBarbados = '&#x1f1e7&#x1f1e7;';
    protected static $flagBangladesh = '&#x1f1e7&#x1f1e9;';
    protected static $flagBelgium = '&#x1f1e7&#x1f1ea;';
    protected static $flagBurkinaFaso = '&#x1f1e7&#x1f1eb;';
    protected static $flagBulgaria = '&#x1f1e7&#x1f1ec;';
    protected static $flagBahrain = '&#x1f1e7&#x1f1ed;';
    protected static $flagBurundi = '&#x1f1e7&#x1f1ee;';
    protected static $flagBenin = '&#x1f1e7&#x1f1ef;';
    protected static $flagStBarthLemy = '&#x1f1e7&#x1f1f1;';
    protected static $flagBermuda = '&#x1f1e7&#x1f1f2;';
    protected static $flagBrunei = '&#x1f1e7&#x1f1f3;';
    protected static $flagBolivia = '&#x1f1e7&#x1f1f4;';
    protected static $flagCaribbeanNetherlands = '&#x1f1e7&#x1f1f6;';
    protected static $flagBrazil = '&#x1f1e7&#x1f1f7;';
    protected static $flagBahamas = '&#x1f1e7&#x1f1f8;';
    protected static $flagBhutan = '&#x1f1e7&#x1f1f9;';
    protected static $flagBouvetIsland = '&#x1f1e7&#x1f1fb;';
    protected static $flagBotswana = '&#x1f1e7&#x1f1fc;';
    protected static $flagBelarus = '&#x1f1e7&#x1f1fe;';
    protected static $flagBelize = '&#x1f1e7&#x1f1ff;';
    protected static $flagCanada = '&#x1f1e8&#x1f1e6;';
    protected static $flagCocosKeelingIslands = '&#x1f1e8&#x1f1e8;';
    protected static $flagCongoKinshasa = '&#x1f1e8&#x1f1e9;';
    protected static $flagCentralAfricanRepublic = '&#x1f1e8&#x1f1eb;';
    protected static $flagCongoBrazzaville = '&#x1f1e8&#x1f1ec;';
    protected static $flagSwitzerland = '&#x1f1e8&#x1f1ed;';
    protected static $flagCTeDIvoire = '&#x1f1e8&#x1f1ee;';
    protected static $flagCookIslands = '&#x1f1e8&#x1f1f0;';
    protected static $flagChile = '&#x1f1e8&#x1f1f1;';
    protected static $flagCameroon = '&#x1f1e8&#x1f1f2;';
    protected static $flagChina = '&#x1f1e8&#x1f1f3;';
    protected static $flagColombia = '&#x1f1e8&#x1f1f4;';
    protected static $flagClippertonIsland = '&#x1f1e8&#x1f1f5;';
    protected static $flagCostaRica = '&#x1f1e8&#x1f1f7;';
    protected static $flagCuba = '&#x1f1e8&#x1f1fa;';
    protected static $flagCapeVerde = '&#x1f1e8&#x1f1fb;';
    protected static $flagCuraAo = '&#x1f1e8&#x1f1fc;';
    protected static $flagChristmasIsland = '&#x1f1e8&#x1f1fd;';
    protected static $flagCyprus = '&#x1f1e8&#x1f1fe;';
    protected static $flagCzechia = '&#x1f1e8&#x1f1ff;';
    protected static $flagGermany = '&#x1f1e9&#x1f1ea;';
    protected static $flagDiegoGarcia = '&#x1f1e9&#x1f1ec;';
    protected static $flagDjibouti = '&#x1f1e9&#x1f1ef;';
    protected static $flagDenmark = '&#x1f1e9&#x1f1f0;';
    protected static $flagDominica = '&#x1f1e9&#x1f1f2;';
    protected static $flagDominicanRepublic = '&#x1f1e9&#x1f1f4;';
    protected static $flagAlgeria = '&#x1f1e9&#x1f1ff;';
    protected static $flagCeutaMelilla = '&#x1f1ea&#x1f1e6;';
    protected static $flagEcuador = '&#x1f1ea&#x1f1e8;';
    protected static $flagEstonia = '&#x1f1ea&#x1f1ea;';
    protected static $flagEgypt = '&#x1f1ea&#x1f1ec;';
    protected static $flagWesternSahara = '&#x1f1ea&#x1f1ed;';
    protected static $flagEritrea = '&#x1f1ea&#x1f1f7;';
    protected static $flagSpain = '&#x1f1ea&#x1f1f8;';
    protected static $flagEthiopia = '&#x1f1ea&#x1f1f9;';
    protected static $flagEuropeanUnion = '&#x1f1ea&#x1f1fa;';
    protected static $flagFinland = '&#x1f1eb&#x1f1ee;';
    protected static $flagFiji = '&#x1f1eb&#x1f1ef;';
    protected static $flagFalklandIslands = '&#x1f1eb&#x1f1f0;';
    protected static $flagMicronesia = '&#x1f1eb&#x1f1f2;';
    protected static $flagFaroeIslands = '&#x1f1eb&#x1f1f4;';
    protected static $flagFrance = '&#x1f1eb&#x1f1f7;';
    protected static $flagGabon = '&#x1f1ec&#x1f1e6;';
    protected static $flagUnitedKingdom = '&#x1f1ec&#x1f1e7;';
    protected static $flagGrenada = '&#x1f1ec&#x1f1e9;';
    protected static $flagGeorgia = '&#x1f1ec&#x1f1ea;';
    protected static $flagFrenchGuiana = '&#x1f1ec&#x1f1eb;';
    protected static $flagGuernsey = '&#x1f1ec&#x1f1ec;';
    protected static $flagGhana = '&#x1f1ec&#x1f1ed;';
    protected static $flagGibraltar = '&#x1f1ec&#x1f1ee;';
    protected static $flagGreenland = '&#x1f1ec&#x1f1f1;';
    protected static $flagGambia = '&#x1f1ec&#x1f1f2;';
    protected static $flagGuinea = '&#x1f1ec&#x1f1f3;';
    protected static $flagGuadeloupe = '&#x1f1ec&#x1f1f5;';
    protected static $flagEquatorialGuinea = '&#x1f1ec&#x1f1f6;';
    protected static $flagGreece = '&#x1f1ec&#x1f1f7;';
    protected static $flagSouthGeorgiaSouthSandwichIslands = '&#x1f1ec&#x1f1f8;';
    protected static $flagGuatemala = '&#x1f1ec&#x1f1f9;';
    protected static $flagGuam = '&#x1f1ec&#x1f1fa;';
    protected static $flagGuineaBissau = '&#x1f1ec&#x1f1fc;';
    protected static $flagGuyana = '&#x1f1ec&#x1f1fe;';
    protected static $flagHongKongSARChina = '&#x1f1ed&#x1f1f0;';
    protected static $flagHeardMcDonaldIslands = '&#x1f1ed&#x1f1f2;';
    protected static $flagHonduras = '&#x1f1ed&#x1f1f3;';
    protected static $flagCroatia = '&#x1f1ed&#x1f1f7;';
    protected static $flagHaiti = '&#x1f1ed&#x1f1f9;';
    protected static $flagHungary = '&#x1f1ed&#x1f1fa;';
    protected static $flagCanaryIslands = '&#x1f1ee&#x1f1e8;';
    protected static $flagIndonesia = '&#x1f1ee&#x1f1e9;';
    protected static $flagIreland = '&#x1f1ee&#x1f1ea;';
    protected static $flagIsrael = '&#x1f1ee&#x1f1f1;';
    protected static $flagIsleOfMan = '&#x1f1ee&#x1f1f2;';
    protected static $flagIndia = '&#x1f1ee&#x1f1f3;';
    protected static $flagBritishIndianOceanTerritory = '&#x1f1ee&#x1f1f4;';
    protected static $flagIraq = '&#x1f1ee&#x1f1f6;';
    protected static $flagIran = '&#x1f1ee&#x1f1f7;';
    protected static $flagIceland = '&#x1f1ee&#x1f1f8;';
    protected static $flagItaly = '&#x1f1ee&#x1f1f9;';
    protected static $flagJersey = '&#x1f1ef&#x1f1ea;';
    protected static $flagJamaica = '&#x1f1ef&#x1f1f2;';
    protected static $flagJordan = '&#x1f1ef&#x1f1f4;';
    protected static $flagJapan = '&#x1f1ef&#x1f1f5;';
    protected static $flagKenya = '&#x1f1f0&#x1f1ea;';
    protected static $flagKyrgyzstan = '&#x1f1f0&#x1f1ec;';
    protected static $flagCambodia = '&#x1f1f0&#x1f1ed;';
    protected static $flagKiribati = '&#x1f1f0&#x1f1ee;';
    protected static $flagComoros = '&#x1f1f0&#x1f1f2;';
    protected static $flagStKittsNevis = '&#x1f1f0&#x1f1f3;';
    protected static $flagNorthKorea = '&#x1f1f0&#x1f1f5;';
    protected static $flagSouthKorea = '&#x1f1f0&#x1f1f7;';
    protected static $flagKuwait = '&#x1f1f0&#x1f1fc;';
    protected static $flagCaymanIslands = '&#x1f1f0&#x1f1fe;';
    protected static $flagKazakhstan = '&#x1f1f0&#x1f1ff;';
    protected static $flagLaos = '&#x1f1f1&#x1f1e6;';
    protected static $flagLebanon = '&#x1f1f1&#x1f1e7;';
    protected static $flagStLucia = '&#x1f1f1&#x1f1e8;';
    protected static $flagLiechtenstein = '&#x1f1f1&#x1f1ee;';
    protected static $flagSriLanka = '&#x1f1f1&#x1f1f0;';
    protected static $flagLiberia = '&#x1f1f1&#x1f1f7;';
    protected static $flagLesotho = '&#x1f1f1&#x1f1f8;';
    protected static $flagLithuania = '&#x1f1f1&#x1f1f9;';
    protected static $flagLuxembourg = '&#x1f1f1&#x1f1fa;';
    protected static $flagLatvia = '&#x1f1f1&#x1f1fb;';
    protected static $flagLibya = '&#x1f1f1&#x1f1fe;';
    protected static $flagMorocco = '&#x1f1f2&#x1f1e6;';
    protected static $flagMonaco = '&#x1f1f2&#x1f1e8;';
    protected static $flagMoldova = '&#x1f1f2&#x1f1e9;';
    protected static $flagMontenegro = '&#x1f1f2&#x1f1ea;';
    protected static $flagStMartin = '&#x1f1f2&#x1f1eb;';
    protected static $flagMadagascar = '&#x1f1f2&#x1f1ec;';
    protected static $flagMarshallIslands = '&#x1f1f2&#x1f1ed;';
    protected static $flagNorthMacedonia = '&#x1f1f2&#x1f1f0;';
    protected static $flagMali = '&#x1f1f2&#x1f1f1;';
    protected static $flagMyanmarBurma = '&#x1f1f2&#x1f1f2;';
    protected static $flagMongolia = '&#x1f1f2&#x1f1f3;';
    protected static $flagMacaoSARChina = '&#x1f1f2&#x1f1f4;';
    protected static $flagNorthernMarianaIslands = '&#x1f1f2&#x1f1f5;';
    protected static $flagMartinique = '&#x1f1f2&#x1f1f6;';
    protected static $flagMauritania = '&#x1f1f2&#x1f1f7;';
    protected static $flagMontserrat = '&#x1f1f2&#x1f1f8;';
    protected static $flagMalta = '&#x1f1f2&#x1f1f9;';
    protected static $flagMauritius = '&#x1f1f2&#x1f1fa;';
    protected static $flagMaldives = '&#x1f1f2&#x1f1fb;';
    protected static $flagMalawi = '&#x1f1f2&#x1f1fc;';
    protected static $flagMexico = '&#x1f1f2&#x1f1fd;';
    protected static $flagMalaysia = '&#x1f1f2&#x1f1fe;';
    protected static $flagMozambique = '&#x1f1f2&#x1f1ff;';
    protected static $flagNamibia = '&#x1f1f3&#x1f1e6;';
    protected static $flagNewCaledonia = '&#x1f1f3&#x1f1e8;';
    protected static $flagNiger = '&#x1f1f3&#x1f1ea;';
    protected static $flagNorfolkIsland = '&#x1f1f3&#x1f1eb;';
    protected static $flagNigeria = '&#x1f1f3&#x1f1ec;';
    protected static $flagNicaragua = '&#x1f1f3&#x1f1ee;';
    protected static $flagNetherlands = '&#x1f1f3&#x1f1f1;';
    protected static $flagNorway = '&#x1f1f3&#x1f1f4;';
    protected static $flagNepal = '&#x1f1f3&#x1f1f5;';
    protected static $flagNauru = '&#x1f1f3&#x1f1f7;';
    protected static $flagNiue = '&#x1f1f3&#x1f1fa;';
    protected static $flagNewZealand = '&#x1f1f3&#x1f1ff;';
    protected static $flagOman = '&#x1f1f4&#x1f1f2;';
    protected static $flagPanama = '&#x1f1f5&#x1f1e6;';
    protected static $flagPeru = '&#x1f1f5&#x1f1ea;';
    protected static $flagFrenchPolynesia = '&#x1f1f5&#x1f1eb;';
    protected static $flagPapuaNewGuinea = '&#x1f1f5&#x1f1ec;';
    protected static $flagPhilippines = '&#x1f1f5&#x1f1ed;';
    protected static $flagPakistan = '&#x1f1f5&#x1f1f0;';
    protected static $flagPoland = '&#x1f1f5&#x1f1f1;';
    protected static $flagStPierreMiquelon = '&#x1f1f5&#x1f1f2;';
    protected static $flagPitcairnIslands = '&#x1f1f5&#x1f1f3;';
    protected static $flagPuertoRico = '&#x1f1f5&#x1f1f7;';
    protected static $flagPalestinianTerritories = '&#x1f1f5&#x1f1f8;';
    protected static $flagPortugal = '&#x1f1f5&#x1f1f9;';
    protected static $flagPalau = '&#x1f1f5&#x1f1fc;';
    protected static $flagParaguay = '&#x1f1f5&#x1f1fe;';
    protected static $flagQatar = '&#x1f1f6&#x1f1e6;';
    protected static $flagRUnion = '&#x1f1f7&#x1f1ea;';
    protected static $flagRomania = '&#x1f1f7&#x1f1f4;';
    protected static $flagSerbia = '&#x1f1f7&#x1f1f8;';
    protected static $flagRussia = '&#x1f1f7&#x1f1fa;';
    protected static $flagRwanda = '&#x1f1f7&#x1f1fc;';
    protected static $flagSaudiArabia = '&#x1f1f8&#x1f1e6;';
    protected static $flagSolomonIslands = '&#x1f1f8&#x1f1e7;';
    protected static $flagSeychelles = '&#x1f1f8&#x1f1e8;';
    protected static $flagSudan = '&#x1f1f8&#x1f1e9;';
    protected static $flagSweden = '&#x1f1f8&#x1f1ea;';
    protected static $flagSingapore = '&#x1f1f8&#x1f1ec;';
    protected static $flagStHelena = '&#x1f1f8&#x1f1ed;';
    protected static $flagSlovenia = '&#x1f1f8&#x1f1ee;';
    protected static $flagSvalbardJanMayen = '&#x1f1f8&#x1f1ef;';
    protected static $flagSlovakia = '&#x1f1f8&#x1f1f0;';
    protected static $flagSierraLeone = '&#x1f1f8&#x1f1f1;';
    protected static $flagSanMarino = '&#x1f1f8&#x1f1f2;';
    protected static $flagSenegal = '&#x1f1f8&#x1f1f3;';
    protected static $flagSomalia = '&#x1f1f8&#x1f1f4;';
    protected static $flagSuriname = '&#x1f1f8&#x1f1f7;';
    protected static $flagSouthSudan = '&#x1f1f8&#x1f1f8;';
    protected static $flagSOTomPrNcipe = '&#x1f1f8&#x1f1f9;';
    protected static $flagElSalvador = '&#x1f1f8&#x1f1fb;';
    protected static $flagSintMaarten = '&#x1f1f8&#x1f1fd;';
    protected static $flagSyria = '&#x1f1f8&#x1f1fe;';
    protected static $flagEswatini = '&#x1f1f8&#x1f1ff;';
    protected static $flagTristanDaCunha = '&#x1f1f9&#x1f1e6;';
    protected static $flagTurksCaicosIslands = '&#x1f1f9&#x1f1e8;';
    protected static $flagChad = '&#x1f1f9&#x1f1e9;';
    protected static $flagFrenchSouthernTerritories = '&#x1f1f9&#x1f1eb;';
    protected static $flagTogo = '&#x1f1f9&#x1f1ec;';
    protected static $flagThailand = '&#x1f1f9&#x1f1ed;';
    protected static $flagTajikistan = '&#x1f1f9&#x1f1ef;';
    protected static $flagTokelau = '&#x1f1f9&#x1f1f0;';
    protected static $flagTimorLeste = '&#x1f1f9&#x1f1f1;';
    protected static $flagTurkmenistan = '&#x1f1f9&#x1f1f2;';
    protected static $flagTunisia = '&#x1f1f9&#x1f1f3;';
    protected static $flagTonga = '&#x1f1f9&#x1f1f4;';
    protected static $flagTurkey = '&#x1f1f9&#x1f1f7;';
    protected static $flagTrinidadTobago = '&#x1f1f9&#x1f1f9;';
    protected static $flagTuvalu = '&#x1f1f9&#x1f1fb;';
    protected static $flagTaiwan = '&#x1f1f9&#x1f1fc;';
    protected static $flagTanzania = '&#x1f1f9&#x1f1ff;';
    protected static $flagUkraine = '&#x1f1fa&#x1f1e6;';
    protected static $flagUganda = '&#x1f1fa&#x1f1ec;';
    protected static $flagUSOutlyingIslands = '&#x1f1fa&#x1f1f2;';
    protected static $flagUnitedNations = '&#x1f1fa&#x1f1f3;';
    protected static $flagUnitedStates = '&#x1f1fa&#x1f1f8;';
    protected static $flagUruguay = '&#x1f1fa&#x1f1fe;';
    protected static $flagUzbekistan = '&#x1f1fa&#x1f1ff;';
    protected static $flagVaticanCity = '&#x1f1fb&#x1f1e6;';
    protected static $flagStVincentGrenadines = '&#x1f1fb&#x1f1e8;';
    protected static $flagVenezuela = '&#x1f1fb&#x1f1ea;';
    protected static $flagBritishVirginIslands = '&#x1f1fb&#x1f1ec;';
    protected static $flagUSVirginIslands = '&#x1f1fb&#x1f1ee;';
    protected static $flagVietnam = '&#x1f1fb&#x1f1f3;';
    protected static $flagVanuatu = '&#x1f1fb&#x1f1fa;';
    protected static $flagWallisFutuna = '&#x1f1fc&#x1f1eb;';
    protected static $flagSamoa = '&#x1f1fc&#x1f1f8;';
    protected static $flagKosovo = '&#x1f1fd&#x1f1f0;';
    protected static $flagYemen = '&#x1f1fe&#x1f1ea;';
    protected static $flagMayotte = '&#x1f1fe&#x1f1f9;';
    protected static $flagSouthAfrica = '&#x1f1ff&#x1f1e6;';
    protected static $flagZambia = '&#x1f1ff&#x1f1f2;';
    protected static $flagZimbabwe = '&#x1f1ff&#x1f1fc;';
}