<?php

namespace TolgaKaragol\Emoji\Traits\Sub\AnimalsNature;

/**
 * Trait AnimalMammalTrait
 * @package TolgaKaragol\Emoji\Traits\Sub\AnimalsNature\AnimalMammalTrait
 *
 * @property string monkeyFace 🐵
 * @property string monkey 🐒
 * @property string gorilla 🦍
 * @property string orangutan 🦧
 * @property string dogFace 🐶
 * @property string dog 🐕
 * @property string guideDog 🦮
 * @property string serviceDog &amp;#x1f415&amp;#x200d🦺
 * @property string poodle 🐩
 * @property string wolf 🐺
 * @property string fox 🦊
 * @property string raccoon 🦝
 * @property string catFace 🐱
 * @property string cat 🐈
 * @property string lion 🦁
 * @property string tigerFace 🐯
 * @property string tiger 🐅
 * @property string leopard 🐆
 * @property string horseFace 🐴
 * @property string horse 🐎
 * @property string unicorn 🦄
 * @property string zebra 🦓
 * @property string deer 🦌
 * @property string cowFace 🐮
 * @property string ox 🐂
 * @property string waterBuffalo 🐃
 * @property string cow 🐄
 * @property string pigFace 🐷
 * @property string pig 🐖
 * @property string boar 🐗
 * @property string pigNose 🐽
 * @property string ram 🐏
 * @property string ewe 🐑
 * @property string goat 🐐
 * @property string camel 🐪
 * @property string twoHumpCamel 🐫
 * @property string llama 🦙
 * @property string giraffe 🦒
 * @property string elephant 🐘
 * @property string rhinoceros 🦏
 * @property string hippopotamus 🦛
 * @property string mouseFace 🐭
 * @property string mouse 🐁
 * @property string rat 🐀
 * @property string hamster 🐹
 * @property string rabbitFace 🐰
 * @property string rabbit 🐇
 * @property string chipmunk 🐿
 * @property string hedgehog 🦔
 * @property string bat 🦇
 * @property string bear 🐻
 * @property string koala 🐨
 * @property string panda 🐼
 * @property string sloth 🦥
 * @property string otter 🦦
 * @property string skunk 🦨
 * @property string kangaroo 🦘
 * @property string badger 🦡
 * @property string pawPrints 🐾
 */
trait AnimalMammalTrait
{
    protected static $monkeyFace = '&#x1f435;';
    protected static $monkey = '&#x1f412;';
    protected static $gorilla = '&#x1f98d;';
    protected static $orangutan = '&#x1f9a7;';
    protected static $dogFace = '&#x1f436;';
    protected static $dog = '&#x1f415;';
    protected static $guideDog = '&#x1f9ae;';
    protected static $serviceDog = '&#x1f415&#x200d&#x1f9ba;';
    protected static $poodle = '&#x1f429;';
    protected static $wolf = '&#x1f43a;';
    protected static $fox = '&#x1f98a;';
    protected static $raccoon = '&#x1f99d;';
    protected static $catFace = '&#x1f431;';
    protected static $cat = '&#x1f408;';
    protected static $lion = '&#x1f981;';
    protected static $tigerFace = '&#x1f42f;';
    protected static $tiger = '&#x1f405;';
    protected static $leopard = '&#x1f406;';
    protected static $horseFace = '&#x1f434;';
    protected static $horse = '&#x1f40e;';
    protected static $unicorn = '&#x1f984;';
    protected static $zebra = '&#x1f993;';
    protected static $deer = '&#x1f98c;';
    protected static $cowFace = '&#x1f42e;';
    protected static $ox = '&#x1f402;';
    protected static $waterBuffalo = '&#x1f403;';
    protected static $cow = '&#x1f404;';
    protected static $pigFace = '&#x1f437;';
    protected static $pig = '&#x1f416;';
    protected static $boar = '&#x1f417;';
    protected static $pigNose = '&#x1f43d;';
    protected static $ram = '&#x1f40f;';
    protected static $ewe = '&#x1f411;';
    protected static $goat = '&#x1f410;';
    protected static $camel = '&#x1f42a;';
    protected static $twoHumpCamel = '&#x1f42b;';
    protected static $llama = '&#x1f999;';
    protected static $giraffe = '&#x1f992;';
    protected static $elephant = '&#x1f418;';
    protected static $rhinoceros = '&#x1f98f;';
    protected static $hippopotamus = '&#x1f99b;';
    protected static $mouseFace = '&#x1f42d;';
    protected static $mouse = '&#x1f401;';
    protected static $rat = '&#x1f400;';
    protected static $hamster = '&#x1f439;';
    protected static $rabbitFace = '&#x1f430;';
    protected static $rabbit = '&#x1f407;';
    protected static $chipmunk = '&#x1f43f;';
    protected static $hedgehog = '&#x1f994;';
    protected static $bat = '&#x1f987;';
    protected static $bear = '&#x1f43b;';
    protected static $koala = '&#x1f428;';
    protected static $panda = '&#x1f43c;';
    protected static $sloth = '&#x1f9a5;';
    protected static $otter = '&#x1f9a6;';
    protected static $skunk = '&#x1f9a8;';
    protected static $kangaroo = '&#x1f998;';
    protected static $badger = '&#x1f9a1;';
    protected static $pawPrints = '&#x1f43e;';
}