<?php

namespace TolgaKaragol\Emoji\Category;

use TolgaKaragol\Emoji\Category\Sub\PeopleBody\HandFingersOpen;
use TolgaKaragol\Emoji\Category\Sub\PeopleBody\HandFingersPartial;
use TolgaKaragol\Emoji\Category\Sub\PeopleBody\HandSingleFinger;
use TolgaKaragol\Emoji\Category\Sub\PeopleBody\HandFingersClosed;
use TolgaKaragol\Emoji\Category\Sub\PeopleBody\Hands;
use TolgaKaragol\Emoji\Category\Sub\PeopleBody\HandProp;
use TolgaKaragol\Emoji\Category\Sub\PeopleBody\BodyParts;
use TolgaKaragol\Emoji\Category\Sub\PeopleBody\Person;
use TolgaKaragol\Emoji\Category\Sub\PeopleBody\PersonGesture;
use TolgaKaragol\Emoji\Category\Sub\PeopleBody\PersonRole;
use TolgaKaragol\Emoji\Category\Sub\PeopleBody\PersonFantasy;
use TolgaKaragol\Emoji\Category\Sub\PeopleBody\PersonActivity;
use TolgaKaragol\Emoji\Category\Sub\PeopleBody\PersonSport;
use TolgaKaragol\Emoji\Category\Sub\PeopleBody\PersonResting;
use TolgaKaragol\Emoji\Category\Sub\PeopleBody\Family;
use TolgaKaragol\Emoji\Category\Sub\PeopleBody\PersonSymbol;
use TolgaKaragol\Emoji\Traits\PeopleBodyTrait;

/**
 * Class PeopleBody
 * @package TolgaKaragol\Emoji\Category\PeopleBody
 *
 * @method static HandFingersOpen handFingersOpen()
 * @method static HandFingersPartial handFingersPartial()
 * @method static HandSingleFinger handSingleFinger()
 * @method static HandFingersClosed handFingersClosed()
 * @method static Hands hands()
 * @method static HandProp handProp()
 * @method static BodyParts bodyParts()
 * @method static Person person()
 * @method static PersonGesture personGesture()
 * @method static PersonRole personRole()
 * @method static PersonFantasy personFantasy()
 * @method static PersonActivity personActivity()
 * @method static PersonSport personSport()
 * @method static PersonResting personResting()
 * @method static Family family()
 * @method static PersonSymbol personSymbol()
 *
 * @property string wavingHand 👋
 * @property string raisedBackOfHand 🤚
 * @property string handWithFingersSplayed 🖐
 * @property string raisedHand ✋
 * @property string vulcanSalute 🖖
 * @property string oKHand 👌
 * @property string pinchingHand 🤏
 * @property string victoryHand ✌
 * @property string crossedFingers 🤞
 * @property string loveYouGesture 🤟
 * @property string signOfTheHorns 🤘
 * @property string callMeHand 🤙
 * @property string backhandIndexPointingLeft 👈
 * @property string backhandIndexPointingRight 👉
 * @property string backhandIndexPointingUp 👆
 * @property string middleFinger 🖕
 * @property string backhandIndexPointingDown 👇
 * @property string indexPointingUp ☝
 * @property string thumbsUp 👍
 * @property string thumbsDown 👎
 * @property string raisedFist ✊
 * @property string oncomingFist 👊
 * @property string leftFacingFist 🤛
 * @property string rightFacingFist 🤜
 * @property string clappingHands 👏
 * @property string raisingHands 🙌
 * @property string openHands 👐
 * @property string palmsUpTogether 🤲
 * @property string handshake 🤝
 * @property string foldedHands 🙏
 * @property string writingHand ✍
 * @property string nailPolish 💅
 * @property string selfie 🤳
 * @property string flexedBiceps 💪
 * @property string mechanicalArm 🦾
 * @property string mechanicalLeg 🦿
 * @property string leg 🦵
 * @property string foot 🦶
 * @property string ear 👂
 * @property string earWithHearingAid 🦻
 * @property string nose 👃
 * @property string brain 🧠
 * @property string tooth 🦷
 * @property string bone 🦴
 * @property string eyes 👀
 * @property string eye 👁
 * @property string tongue 👅
 * @property string mouth 👄
 * @property string baby 👶
 * @property string child 🧒
 * @property string boy 👦
 * @property string girl 👧
 * @property string person 🧑
 * @property string personBlondHair 👱
 * @property string man 👨
 * @property string manBeard 🧔
 * @property string manRedHair &amp;#x1f468&amp;#x200d🦰
 * @property string manCurlyHair &amp;#x1f468&amp;#x200d🦱
 * @property string manWhiteHair &amp;#x1f468&amp;#x200d🦳
 * @property string manBald &amp;#x1f468&amp;#x200d🦲
 * @property string woman 👩
 * @property string womanRedHair &amp;#x1f469&amp;#x200d🦰
 * @property string personRedHair &amp;#x1f9d1&amp;#x200d🦰
 * @property string womanCurlyHair &amp;#x1f469&amp;#x200d🦱
 * @property string personCurlyHair &amp;#x1f9d1&amp;#x200d🦱
 * @property string womanWhiteHair &amp;#x1f469&amp;#x200d🦳
 * @property string personWhiteHair &amp;#x1f9d1&amp;#x200d🦳
 * @property string womanBald &amp;#x1f469&amp;#x200d🦲
 * @property string personBald &amp;#x1f9d1&amp;#x200d🦲
 * @property string womanBlondHair &amp;#x1f471&amp;#x200d&amp;#x2640️
 * @property string manBlondHair &amp;#x1f471&amp;#x200d&amp;#x2642️
 * @property string olderPerson 🧓
 * @property string oldMan 👴
 * @property string oldWoman 👵
 * @property string personFrowning 🙍
 * @property string manFrowning &amp;#x1f64d&amp;#x200d&amp;#x2642️
 * @property string womanFrowning &amp;#x1f64d&amp;#x200d&amp;#x2640️
 * @property string personPouting 🙎
 * @property string manPouting &amp;#x1f64e&amp;#x200d&amp;#x2642️
 * @property string womanPouting &amp;#x1f64e&amp;#x200d&amp;#x2640️
 * @property string personGesturingNO 🙅
 * @property string manGesturingNO &amp;#x1f645&amp;#x200d&amp;#x2642️
 * @property string womanGesturingNO &amp;#x1f645&amp;#x200d&amp;#x2640️
 * @property string personGesturingOK 🙆
 * @property string manGesturingOK &amp;#x1f646&amp;#x200d&amp;#x2642️
 * @property string womanGesturingOK &amp;#x1f646&amp;#x200d&amp;#x2640️
 * @property string personTippingHand 💁
 * @property string manTippingHand &amp;#x1f481&amp;#x200d&amp;#x2642️
 * @property string womanTippingHand &amp;#x1f481&amp;#x200d&amp;#x2640️
 * @property string personRaisingHand 🙋
 * @property string manRaisingHand &amp;#x1f64b&amp;#x200d&amp;#x2642️
 * @property string womanRaisingHand &amp;#x1f64b&amp;#x200d&amp;#x2640️
 * @property string deafPerson 🧏
 * @property string deafMan &amp;#x1f9cf&amp;#x200d&amp;#x2642️
 * @property string deafWoman &amp;#x1f9cf&amp;#x200d&amp;#x2640️
 * @property string personBowing 🙇
 * @property string manBowing &amp;#x1f647&amp;#x200d&amp;#x2642️
 * @property string womanBowing &amp;#x1f647&amp;#x200d&amp;#x2640️
 * @property string personFacepalming 🤦
 * @property string manFacepalming &amp;#x1f926&amp;#x200d&amp;#x2642️
 * @property string womanFacepalming &amp;#x1f926&amp;#x200d&amp;#x2640️
 * @property string personShrugging 🤷
 * @property string manShrugging &amp;#x1f937&amp;#x200d&amp;#x2642️
 * @property string womanShrugging &amp;#x1f937&amp;#x200d&amp;#x2640️
 * @property string healthWorker &amp;#x1f9d1&amp;#x200d&amp;#x2695️
 * @property string manHealthWorker &amp;#x1f468&amp;#x200d&amp;#x2695️
 * @property string womanHealthWorker &amp;#x1f469&amp;#x200d&amp;#x2695️
 * @property string student &amp;#x1f9d1&amp;#x200d🎓
 * @property string manStudent &amp;#x1f468&amp;#x200d🎓
 * @property string womanStudent &amp;#x1f469&amp;#x200d🎓
 * @property string teacher &amp;#x1f9d1&amp;#x200d🏫
 * @property string manTeacher &amp;#x1f468&amp;#x200d🏫
 * @property string womanTeacher &amp;#x1f469&amp;#x200d🏫
 * @property string judge &amp;#x1f9d1&amp;#x200d&amp;#x2696️
 * @property string manJudge &amp;#x1f468&amp;#x200d&amp;#x2696️
 * @property string womanJudge &amp;#x1f469&amp;#x200d&amp;#x2696️
 * @property string farmer &amp;#x1f9d1&amp;#x200d🌾
 * @property string manFarmer &amp;#x1f468&amp;#x200d🌾
 * @property string womanFarmer &amp;#x1f469&amp;#x200d🌾
 * @property string cook &amp;#x1f9d1&amp;#x200d🍳
 * @property string manCook &amp;#x1f468&amp;#x200d🍳
 * @property string womanCook &amp;#x1f469&amp;#x200d🍳
 * @property string mechanic &amp;#x1f9d1&amp;#x200d🔧
 * @property string manMechanic &amp;#x1f468&amp;#x200d🔧
 * @property string womanMechanic &amp;#x1f469&amp;#x200d🔧
 * @property string factoryWorker &amp;#x1f9d1&amp;#x200d🏭
 * @property string manFactoryWorker &amp;#x1f468&amp;#x200d🏭
 * @property string womanFactoryWorker &amp;#x1f469&amp;#x200d🏭
 * @property string officeWorker &amp;#x1f9d1&amp;#x200d💼
 * @property string manOfficeWorker &amp;#x1f468&amp;#x200d💼
 * @property string womanOfficeWorker &amp;#x1f469&amp;#x200d💼
 * @property string scientist &amp;#x1f9d1&amp;#x200d🔬
 * @property string manScientist &amp;#x1f468&amp;#x200d🔬
 * @property string womanScientist &amp;#x1f469&amp;#x200d🔬
 * @property string technologist &amp;#x1f9d1&amp;#x200d💻
 * @property string manTechnologist &amp;#x1f468&amp;#x200d💻
 * @property string womanTechnologist &amp;#x1f469&amp;#x200d💻
 * @property string singer &amp;#x1f9d1&amp;#x200d🎤
 * @property string manSinger &amp;#x1f468&amp;#x200d🎤
 * @property string womanSinger &amp;#x1f469&amp;#x200d🎤
 * @property string artist &amp;#x1f9d1&amp;#x200d🎨
 * @property string manArtist &amp;#x1f468&amp;#x200d🎨
 * @property string womanArtist &amp;#x1f469&amp;#x200d🎨
 * @property string pilot &amp;#x1f9d1&amp;#x200d&amp;#x2708️
 * @property string manPilot &amp;#x1f468&amp;#x200d&amp;#x2708️
 * @property string womanPilot &amp;#x1f469&amp;#x200d&amp;#x2708️
 * @property string astronaut &amp;#x1f9d1&amp;#x200d🚀
 * @property string manAstronaut &amp;#x1f468&amp;#x200d🚀
 * @property string womanAstronaut &amp;#x1f469&amp;#x200d🚀
 * @property string firefighter &amp;#x1f9d1&amp;#x200d🚒
 * @property string manFirefighter &amp;#x1f468&amp;#x200d🚒
 * @property string womanFirefighter &amp;#x1f469&amp;#x200d🚒
 * @property string policeOfficer 👮
 * @property string manPoliceOfficer &amp;#x1f46e&amp;#x200d&amp;#x2642️
 * @property string womanPoliceOfficer &amp;#x1f46e&amp;#x200d&amp;#x2640️
 * @property string detective 🕵
 * @property string manDetective &amp;#x1f575&amp;#xfe0f&amp;#x200d&amp;#x2642️
 * @property string womanDetective &amp;#x1f575&amp;#xfe0f&amp;#x200d&amp;#x2640️
 * @property string guard 💂
 * @property string manGuard &amp;#x1f482&amp;#x200d&amp;#x2642️
 * @property string womanGuard &amp;#x1f482&amp;#x200d&amp;#x2640️
 * @property string constructionWorker 👷
 * @property string manConstructionWorker &amp;#x1f477&amp;#x200d&amp;#x2642️
 * @property string womanConstructionWorker &amp;#x1f477&amp;#x200d&amp;#x2640️
 * @property string prince 🤴
 * @property string princess 👸
 * @property string personWearingTurban 👳
 * @property string manWearingTurban &amp;#x1f473&amp;#x200d&amp;#x2642️
 * @property string womanWearingTurban &amp;#x1f473&amp;#x200d&amp;#x2640️
 * @property string manWithSkullcap 👲
 * @property string womanWithHeadscarf 🧕
 * @property string manInTuxedo 🤵
 * @property string brideWithVeil 👰
 * @property string pregnantWoman 🤰
 * @property string breastFeeding 🤱
 * @property string babyAngel 👼
 * @property string santaClaus 🎅
 * @property string mrsClaus 🤶
 * @property string superhero 🦸
 * @property string manSuperhero &amp;#x1f9b8&amp;#x200d&amp;#x2642️
 * @property string womanSuperhero &amp;#x1f9b8&amp;#x200d&amp;#x2640️
 * @property string supervillain 🦹
 * @property string manSupervillain &amp;#x1f9b9&amp;#x200d&amp;#x2642️
 * @property string womanSupervillain &amp;#x1f9b9&amp;#x200d&amp;#x2640️
 * @property string mage 🧙
 * @property string manMage &amp;#x1f9d9&amp;#x200d&amp;#x2642️
 * @property string womanMage &amp;#x1f9d9&amp;#x200d&amp;#x2640️
 * @property string fairy 🧚
 * @property string manFairy &amp;#x1f9da&amp;#x200d&amp;#x2642️
 * @property string womanFairy &amp;#x1f9da&amp;#x200d&amp;#x2640️
 * @property string vampire 🧛
 * @property string manVampire &amp;#x1f9db&amp;#x200d&amp;#x2642️
 * @property string womanVampire &amp;#x1f9db&amp;#x200d&amp;#x2640️
 * @property string merperson 🧜
 * @property string merman &amp;#x1f9dc&amp;#x200d&amp;#x2642️
 * @property string mermaid &amp;#x1f9dc&amp;#x200d&amp;#x2640️
 * @property string elf 🧝
 * @property string manElf &amp;#x1f9dd&amp;#x200d&amp;#x2642️
 * @property string womanElf &amp;#x1f9dd&amp;#x200d&amp;#x2640️
 * @property string genie 🧞
 * @property string manGenie &amp;#x1f9de&amp;#x200d&amp;#x2642️
 * @property string womanGenie &amp;#x1f9de&amp;#x200d&amp;#x2640️
 * @property string zombie 🧟
 * @property string manZombie &amp;#x1f9df&amp;#x200d&amp;#x2642️
 * @property string womanZombie &amp;#x1f9df&amp;#x200d&amp;#x2640️
 * @property string personGettingMassage 💆
 * @property string manGettingMassage &amp;#x1f486&amp;#x200d&amp;#x2642️
 * @property string womanGettingMassage &amp;#x1f486&amp;#x200d&amp;#x2640️
 * @property string personGettingHaircut 💇
 * @property string manGettingHaircut &amp;#x1f487&amp;#x200d&amp;#x2642️
 * @property string womanGettingHaircut &amp;#x1f487&amp;#x200d&amp;#x2640️
 * @property string personWalking 🚶
 * @property string manWalking &amp;#x1f6b6&amp;#x200d&amp;#x2642️
 * @property string womanWalking &amp;#x1f6b6&amp;#x200d&amp;#x2640️
 * @property string personStanding 🧍
 * @property string manStanding &amp;#x1f9cd&amp;#x200d&amp;#x2642️
 * @property string womanStanding &amp;#x1f9cd&amp;#x200d&amp;#x2640️
 * @property string personKneeling 🧎
 * @property string manKneeling &amp;#x1f9ce&amp;#x200d&amp;#x2642️
 * @property string womanKneeling &amp;#x1f9ce&amp;#x200d&amp;#x2640️
 * @property string personWithProbingCane &amp;#x1f9d1&amp;#x200d🦯
 * @property string manWithProbingCane &amp;#x1f468&amp;#x200d🦯
 * @property string womanWithProbingCane &amp;#x1f469&amp;#x200d🦯
 * @property string personInMotorizedWheelchair &amp;#x1f9d1&amp;#x200d🦼
 * @property string manInMotorizedWheelchair &amp;#x1f468&amp;#x200d🦼
 * @property string womanInMotorizedWheelchair &amp;#x1f469&amp;#x200d🦼
 * @property string personInManualWheelchair &amp;#x1f9d1&amp;#x200d🦽
 * @property string manInManualWheelchair &amp;#x1f468&amp;#x200d🦽
 * @property string womanInManualWheelchair &amp;#x1f469&amp;#x200d🦽
 * @property string personRunning 🏃
 * @property string manRunning &amp;#x1f3c3&amp;#x200d&amp;#x2642️
 * @property string womanRunning &amp;#x1f3c3&amp;#x200d&amp;#x2640️
 * @property string womanDancing 💃
 * @property string manDancing 🕺
 * @property string manInSuitLevitating 🕴
 * @property string peopleWithBunnyEars 👯
 * @property string menWithBunnyEars &amp;#x1f46f&amp;#x200d&amp;#x2642️
 * @property string womenWithBunnyEars &amp;#x1f46f&amp;#x200d&amp;#x2640️
 * @property string personInSteamyRoom 🧖
 * @property string manInSteamyRoom &amp;#x1f9d6&amp;#x200d&amp;#x2642️
 * @property string womanInSteamyRoom &amp;#x1f9d6&amp;#x200d&amp;#x2640️
 * @property string personClimbing 🧗
 * @property string manClimbing &amp;#x1f9d7&amp;#x200d&amp;#x2642️
 * @property string womanClimbing &amp;#x1f9d7&amp;#x200d&amp;#x2640️
 * @property string personFencing 🤺
 * @property string horseRacing 🏇
 * @property string skier ⛷
 * @property string snowboarder 🏂
 * @property string personGolfing 🏌
 * @property string manGolfing &amp;#x1f3cc&amp;#xfe0f&amp;#x200d&amp;#x2642️
 * @property string womanGolfing &amp;#x1f3cc&amp;#xfe0f&amp;#x200d&amp;#x2640️
 * @property string personSurfing 🏄
 * @property string manSurfing &amp;#x1f3c4&amp;#x200d&amp;#x2642️
 * @property string womanSurfing &amp;#x1f3c4&amp;#x200d&amp;#x2640️
 * @property string personRowingBoat 🚣
 * @property string manRowingBoat &amp;#x1f6a3&amp;#x200d&amp;#x2642️
 * @property string womanRowingBoat &amp;#x1f6a3&amp;#x200d&amp;#x2640️
 * @property string personSwimming 🏊
 * @property string manSwimming &amp;#x1f3ca&amp;#x200d&amp;#x2642️
 * @property string womanSwimming &amp;#x1f3ca&amp;#x200d&amp;#x2640️
 * @property string personBouncingBall ⛹
 * @property string manBouncingBall &amp;#x26f9&amp;#xfe0f&amp;#x200d&amp;#x2642️
 * @property string womanBouncingBall &amp;#x26f9&amp;#xfe0f&amp;#x200d&amp;#x2640️
 * @property string personLiftingWeights 🏋
 * @property string manLiftingWeights &amp;#x1f3cb&amp;#xfe0f&amp;#x200d&amp;#x2642️
 * @property string womanLiftingWeights &amp;#x1f3cb&amp;#xfe0f&amp;#x200d&amp;#x2640️
 * @property string personBiking 🚴
 * @property string manBiking &amp;#x1f6b4&amp;#x200d&amp;#x2642️
 * @property string womanBiking &amp;#x1f6b4&amp;#x200d&amp;#x2640️
 * @property string personMountainBiking 🚵
 * @property string manMountainBiking &amp;#x1f6b5&amp;#x200d&amp;#x2642️
 * @property string womanMountainBiking &amp;#x1f6b5&amp;#x200d&amp;#x2640️
 * @property string personCartwheeling 🤸
 * @property string manCartwheeling &amp;#x1f938&amp;#x200d&amp;#x2642️
 * @property string womanCartwheeling &amp;#x1f938&amp;#x200d&amp;#x2640️
 * @property string peopleWrestling 🤼
 * @property string menWrestling &amp;#x1f93c&amp;#x200d&amp;#x2642️
 * @property string womenWrestling &amp;#x1f93c&amp;#x200d&amp;#x2640️
 * @property string personPlayingWaterPolo 🤽
 * @property string manPlayingWaterPolo &amp;#x1f93d&amp;#x200d&amp;#x2642️
 * @property string womanPlayingWaterPolo &amp;#x1f93d&amp;#x200d&amp;#x2640️
 * @property string personPlayingHandball 🤾
 * @property string manPlayingHandball &amp;#x1f93e&amp;#x200d&amp;#x2642️
 * @property string womanPlayingHandball &amp;#x1f93e&amp;#x200d&amp;#x2640️
 * @property string personJuggling 🤹
 * @property string manJuggling &amp;#x1f939&amp;#x200d&amp;#x2642️
 * @property string womanJuggling &amp;#x1f939&amp;#x200d&amp;#x2640️
 * @property string personInLotusPosition 🧘
 * @property string manInLotusPosition &amp;#x1f9d8&amp;#x200d&amp;#x2642️
 * @property string womanInLotusPosition &amp;#x1f9d8&amp;#x200d&amp;#x2640️
 * @property string personTakingBath 🛀
 * @property string personInBed 🛌
 * @property string peopleHoldingHands &amp;#x1f9d1&amp;#x200d&amp;#x1f91d&amp;#x200d🧑
 * @property string womenHoldingHands 👭
 * @property string womanAndManHoldingHands 👫
 * @property string menHoldingHands 👬
 * @property string kiss 💏
 * @property string kissWomanMan &amp;#x1f469&amp;#x200d&amp;#x2764&amp;#xfe0f&amp;#x200d&amp;#x1f48b&amp;#x200d👨
 * @property string kissManMan &amp;#x1f468&amp;#x200d&amp;#x2764&amp;#xfe0f&amp;#x200d&amp;#x1f48b&amp;#x200d👨
 * @property string kissWomanWoman &amp;#x1f469&amp;#x200d&amp;#x2764&amp;#xfe0f&amp;#x200d&amp;#x1f48b&amp;#x200d👩
 * @property string coupleWithHeart 💑
 * @property string coupleWithHeartWomanMan &amp;#x1f469&amp;#x200d&amp;#x2764&amp;#xfe0f&amp;#x200d👨
 * @property string coupleWithHeartManMan &amp;#x1f468&amp;#x200d&amp;#x2764&amp;#xfe0f&amp;#x200d👨
 * @property string coupleWithHeartWomanWoman &amp;#x1f469&amp;#x200d&amp;#x2764&amp;#xfe0f&amp;#x200d👩
 * @property string family 👪
 * @property string familyManWomanBoy &amp;#x1f468&amp;#x200d&amp;#x1f469&amp;#x200d👦
 * @property string familyManWomanGirl &amp;#x1f468&amp;#x200d&amp;#x1f469&amp;#x200d👧
 * @property string familyManWomanGirlBoy &amp;#x1f468&amp;#x200d&amp;#x1f469&amp;#x200d&amp;#x1f467&amp;#x200d👦
 * @property string familyManWomanBoyBoy &amp;#x1f468&amp;#x200d&amp;#x1f469&amp;#x200d&amp;#x1f466&amp;#x200d👦
 * @property string familyManWomanGirlGirl &amp;#x1f468&amp;#x200d&amp;#x1f469&amp;#x200d&amp;#x1f467&amp;#x200d👧
 * @property string familyManManBoy &amp;#x1f468&amp;#x200d&amp;#x1f468&amp;#x200d👦
 * @property string familyManManGirl &amp;#x1f468&amp;#x200d&amp;#x1f468&amp;#x200d👧
 * @property string familyManManGirlBoy &amp;#x1f468&amp;#x200d&amp;#x1f468&amp;#x200d&amp;#x1f467&amp;#x200d👦
 * @property string familyManManBoyBoy &amp;#x1f468&amp;#x200d&amp;#x1f468&amp;#x200d&amp;#x1f466&amp;#x200d👦
 * @property string familyManManGirlGirl &amp;#x1f468&amp;#x200d&amp;#x1f468&amp;#x200d&amp;#x1f467&amp;#x200d👧
 * @property string familyWomanWomanBoy &amp;#x1f469&amp;#x200d&amp;#x1f469&amp;#x200d👦
 * @property string familyWomanWomanGirl &amp;#x1f469&amp;#x200d&amp;#x1f469&amp;#x200d👧
 * @property string familyWomanWomanGirlBoy &amp;#x1f469&amp;#x200d&amp;#x1f469&amp;#x200d&amp;#x1f467&amp;#x200d👦
 * @property string familyWomanWomanBoyBoy &amp;#x1f469&amp;#x200d&amp;#x1f469&amp;#x200d&amp;#x1f466&amp;#x200d👦
 * @property string familyWomanWomanGirlGirl &amp;#x1f469&amp;#x200d&amp;#x1f469&amp;#x200d&amp;#x1f467&amp;#x200d👧
 * @property string familyManBoy &amp;#x1f468&amp;#x200d👦
 * @property string familyManBoyBoy &amp;#x1f468&amp;#x200d&amp;#x1f466&amp;#x200d👦
 * @property string familyManGirl &amp;#x1f468&amp;#x200d👧
 * @property string familyManGirlBoy &amp;#x1f468&amp;#x200d&amp;#x1f467&amp;#x200d👦
 * @property string familyManGirlGirl &amp;#x1f468&amp;#x200d&amp;#x1f467&amp;#x200d👧
 * @property string familyWomanBoy &amp;#x1f469&amp;#x200d👦
 * @property string familyWomanBoyBoy &amp;#x1f469&amp;#x200d&amp;#x1f466&amp;#x200d👦
 * @property string familyWomanGirl &amp;#x1f469&amp;#x200d👧
 * @property string familyWomanGirlBoy &amp;#x1f469&amp;#x200d&amp;#x1f467&amp;#x200d👦
 * @property string familyWomanGirlGirl &amp;#x1f469&amp;#x200d&amp;#x1f467&amp;#x200d👧
 * @property string speakingHead 🗣
 * @property string bustInSilhouette 👤
 * @property string bustsInSilhouette 👥
 * @property string footprints 👣
 */
class PeopleBody
{
    use PeopleBodyTrait;

}